(function(g){var window=this;'use strict';var ZwH=function(n,m){g.Ht(n,"onAutonavCoundownStarted",m)},X$q=function(n){return n.isBackground()&&n.JM()},Low=function(n,m){m=m.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
n.Z=m?.navigationEndpoint;m=m?.trackingParams;n.playButton&&m&&n.V.setTrackingParams(n.playButton.element,m)},Av=function(n){const m=ze(n);
var M=Math,h=M.min;var F=n.N?Date.now()-n.N:0;M=h.call(M,F,m);oI(n,Math.ceil((m-M)/1E3));m-M<=500&&n.U()?n.select(!0):n.U()&&n.C.start()},b_=function(n){var m=n.V.nR(!0,n.V.isFullscreen());
g.C(n.container.element,"ytp-autonav-endscreen-small-mode",n.wD(m));g.C(n.container.element,"ytp-autonav-endscreen-is-premium",!!n.suggestion&&!!n.suggestion.Am);g.C(n.V.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!n.V.hN());g.C(n.V.getRootNode(),"countdown-running",n.U());g.C(n.container.element,"ytp-player-content",n.V.hN());n.V.O("web_post_play_autonav_embiggening")||g.mI(n.overlay.element,{width:`${m.width}px`});if(n.V.O("web_post_play_autonav_embiggening")){var M=n.V.getRootNode().getBoundingClientRect();
m=Math.min(720,M.width*.5);var h=m*.5625;M=M.height-36-60;h>M&&(h=M,m=16/9*h);g.mI(n.j.m7("ytp-autonav-endscreen-upnext-thumbnail"),{height:`${h}px`,width:`${m}px`});g.mI(n.container.element,{width:`${m}px`})}n.U()||(n.V.hN()?oI(n,Math.round(ze(n)/1E3)):oI(n),m=!!n.suggestion&&!!n.suggestion.c5,h=n.V.hN()||!m,g.C(n.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!h&&m),g.C(n.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",h&&!m),n.A.hF(n.V.hN()))},oI=
function(n,m=-1){n=n.j.m7("ytp-autonav-endscreen-upnext-header");
g.jL(n);if(m>=0){m=String(m);const M="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],h="Up next in $SECONDS".indexOf(M);if(h>=0){n.appendChild(g.Ia("Up next in $SECONDS".slice(0,h)));const F=g.gg("span");g.Vj(F,"ytp-autonav-endscreen-upnext-header-countdown-number");g.KV(F,m);n.appendChild(F);n.appendChild(g.Ia("Up next in $SECONDS".slice(h+M.length)));return}}g.KV(n,"Up next")},ze=function(n){return n.V.isFullscreen()?(n=n.V.getVideoData()?.EN,n===-1||n===void 0?8E3:n):n.V.g6()>=0?n.V.g6():
g.PN(n.V.D().experiments,"autoplay_time")||1E4},BT=function(n,m){m=gaq(n,m);
var M=Math,h=M.min;var F=(0,g.l)()-n.N;M=h.call(M,F,m);m=m===0?1:Math.min(M/m,1);n.BT.setAttribute("stroke-dashoffset",`${-211*(m+1)}`);m>=1&&n.U()&&n.api.getPresentingPlayerType()!==3?n.select(!0):n.U()&&n.j.start()},gaq=function(n,m){return m?m:n.api.isFullscreen()?(n=n.api.getVideoData()?.EN,n===-1||n===void 0?8E3:n):n.api.g6()>=0?n.api.g6():g.PN(n.api.D().experiments,"autoplay_time")||1E4},aI=function(n){return g.RF(n.player)&&n.C()&&!n.W},Vp=function(n){const m=n.hN();
m!==n.Y&&(n.Y=m,n.player.publish("autonavvisibility"))},xo=function(n){return g.RF(n.player)&&n.C()&&!n.B},wN=function(n){const m=n.hN();
m!==n.fP&&(n.fP=m,n.player.publish("autonavvisibility"))},IWo=function(n){n=n.D();
return n.LY&&!n.JN&&!n.disableOrganicUi},$o7=function(n){const m=n.player.getVideoData();
if(!m||n.U===m.xq)return!1;n.U=m.xq;return!0},jc6=function(n){n.player.Aj("endscreen");
var m=n.player.getVideoData();m=new g.OW(Math.max((m.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});const M=new g.OW(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});n.player.pF([m,M])};
g.xz.prototype.g6=g.M7(9,function(){return this.app.g6()});
g.iR.prototype.g6=g.M7(8,function(){return this.getVideoData().nz});
g.Vw.prototype.D$=g.M7(7,function(n){this.NU().D$(n)});
g.XU.prototype.D$=g.M7(6,function(n){this.Ki!==n&&(this.Ki=n,this.XT())});
var yp=class extends g.U{constructor(n){super({K:"div",J:"ytp-autonav-endscreen-countdown-overlay"});this.cancelCommand=this.Z=void 0;this.N=0;n.O("web_post_play_autonav_embiggening")&&g.wo(this.element,"ytp-autonav-endscreen-upnext-updated");this.container=new g.U({K:"div",J:"ytp-autonav-endscreen-countdown-container"});g.L(this,this.container);this.container.Qi(this.element);var m=n.D();const M=m.W;this.V=n;this.suggestion=null;this.onVideoDataChange("newdata",this.V.getVideoData());this.L(n,"videodatachange",
this.onVideoDataChange);this.j=new g.U({K:"div",J:"ytp-autonav-endscreen-upnext-container",S:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},G:[{K:"div",J:"ytp-autonav-endscreen-topbar-container",G:[{K:"div",J:"ytp-autonav-endscreen-upnext-header"},{K:"div",J:"ytp-autonav-endscreen-upnext-alternative-header",PT:"{{autoplayAlternativeHeader}}"}]},{K:"a",J:"ytp-autonav-endscreen-link-container",
S:{href:"{{url}}",target:M?m.Y:""},G:[{K:"div",J:"ytp-autonav-endscreen-upnext-thumbnail",S:{style:"{{background}}"},G:[{K:"div",S:{"aria-label":"{{timestamp}}"},Vi:["ytp-autonav-timestamp"],PT:"{{duration}}"},{K:"div",Vi:["ytp-autonav-live-stamp"],PT:"Live"},{K:"div",Vi:["ytp-autonav-upcoming-stamp"],PT:"Upcoming"}]},{K:"div",J:"ytp-autonav-endscreen-video-info",G:[{K:"div",J:"ytp-autonav-endscreen-premium-badge"},{K:"div",J:"ytp-autonav-endscreen-upnext-title",PT:"{{title}}"},{K:"div",J:"ytp-autonav-endscreen-upnext-author",
PT:"{{author}}"},{K:"div",J:"ytp-autonav-view-and-date",PT:"{{views_and_publish_time}}"},{K:"div",J:"ytp-autonav-author-and-view",PT:"{{author_and_views}}"}]}]}]});g.L(this,this.j);this.j.Qi(this.container.element);M||this.L(this.j.m7("ytp-autonav-endscreen-link-container"),"click",this.lq);this.V.createClientVe(this.container.element,this,115127);this.V.createClientVe(this.j.m7("ytp-autonav-endscreen-link-container"),this,115128);this.closeButton=new g.U({K:"button",J:"ytp-autonav-endscreen-upnext-header-close-button",
S:{"aria-label":"Cancel autoplay"}});g.L(this,this.closeButton);n.O("web_post_play_autonav_embiggening")&&(this.closeButton.listen("click",this.Uw,this),this.V.createClientVe(this.closeButton.element,this,115129),this.j.m7("ytp-autonav-endscreen-topbar-container").appendChild(this.closeButton.element));this.overlay=new g.U({K:"div",J:"ytp-autonav-overlay"});g.L(this,this.overlay);this.overlay.Qi(this.container.element);this.A=new g.U({K:"div",J:"ytp-autonav-endscreen-button-container"});g.L(this,
this.A);this.A.Qi(this.container.element);this.cancelButton=new g.U({K:"button",Vi:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],S:{"aria-label":"Cancel autoplay"},PT:"Cancel"});g.L(this,this.cancelButton);this.cancelButton.Qi(this.A.element);this.cancelButton.listen("click",this.Uw,this);this.V.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.U({K:"a",Vi:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button","ytp-autonav-endscreen-upnext-button-rounded"],S:{href:"{{url}}",role:"button","aria-label":"Play next video"},PT:"Play Now"});g.L(this,this.playButton);this.playButton.Qi(this.A.element);this.playButton.listen("click",this.lq,this);this.V.createServerVe(this.playButton.element,this.playButton,!0);(m=this.V.getVideoData())&&Low(this,m);this.C=new g.o9(()=>{Av(this)},500);
g.L(this,this.C);this.fP();this.L(n,"autonavvisibility",this.fP)}Y(n){this.suggestion!==n&&(this.suggestion=n,g.N6(this.j,n),this.playButton.updateValue("url",this.suggestion.TA()),b_(this))}U(){return this.N>0}B(){this.U()||(this.N=Date.now(),Av(this),ZwH(this.V,ze(this)),g.C(this.V.getRootNode(),"countdown-running",this.U()))}W(){this.X();Av(this);const n=this.j.m7("ytp-autonav-endscreen-upnext-header");n&&g.KV(n,"Up next")}X(){this.U()&&(this.C.stop(),this.N=0)}select(n=!1){this.V.nextVideo(!1,
n);this.X()}lq(n){g.ln(n,this.V)&&(n.currentTarget===this.playButton.element?this.V.logClick(this.playButton.element):n.currentTarget===this.j.m7("ytp-autonav-endscreen-link-container")&&(n=this.j.m7("ytp-autonav-endscreen-link-container"),this.V.logVisibility(n,!0),this.V.logClick(n)),this.Z?(g.Ht(this.V,"innertubeCommand",this.Z),this.X()):this.select())}Uw(){this.V.logClick(this.cancelButton.element);g.ZV(this.V,!0);this.cancelCommand&&g.Ht(this.V,"innertubeCommand",this.cancelCommand)}onVideoDataChange(n,
m){Low(this,m);this.cancelCommand=m.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}fP(){const n=this.V.hN();this.Xq!==n&&this.hF(n);b_(this);this.V.logVisibility(this.container.element,n);this.V.logVisibility(this.cancelButton.element,n);this.V.logVisibility(this.j.m7("ytp-autonav-endscreen-link-container"),n);this.V.logVisibility(this.playButton.element,n)}wD(n){return n.width<400||n.height<459}};var Ni=class extends g.U{constructor(n,m){super({K:"div",Vi:["html5-endscreen","ytp-player-content",m||"base-endscreen"]});this.created=!1;this.player=n}create(){this.created=!0}destroy(){this.created=!1}C(){return!1}hN(){return!1}Z(){return!1}};var Rfm=class extends g.U{constructor(n){super({K:"div",Vi:["ytp-upnext","ytp-player-content"],S:{"aria-label":"{{aria_label}}"},G:[{K:"div",J:"ytp-cued-thumbnail-overlay-image",S:{style:"{{background}}"}},{K:"span",J:"ytp-upnext-top",G:[{K:"span",J:"ytp-upnext-header",PT:"Up Next"},{K:"span",J:"ytp-upnext-title",PT:"{{title}}"},{K:"span",J:"ytp-upnext-author",PT:"{{author}}"}]},{K:"a",J:"ytp-upnext-autoplay-icon",S:{role:"button",href:"{{url}}","aria-label":"Play next video"},G:[{K:"svg",S:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},G:[{K:"circle",J:"ytp-svg-autoplay-circle",S:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{K:"circle",J:"ytp-svg-autoplay-ring",S:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{K:"path",J:"ytp-svg-fill",S:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{K:"span",J:"ytp-upnext-bottom",G:[{K:"span",J:"ytp-upnext-cancel"},
{K:"span",J:"ytp-upnext-paused",PT:"Autoplay is paused"}]}]});this.api=n;this.cancelButton=null;this.BT=this.m7("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.Z=new g.o9(this.A,5E3,this);this.N=0;var m=this.m7("ytp-upnext-cancel");this.cancelButton=new g.U({K:"button",Vi:["ytp-upnext-cancel-button","ytp-button"],S:{tabindex:"0","aria-label":"Cancel autoplay"},PT:"Cancel"});g.L(this,this.cancelButton);this.cancelButton.listen("click",this.Uw,this);this.cancelButton.Qi(m);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.L(this,this.Z);this.api.createClientVe(this.element,this,18788);m=this.m7("ytp-upnext-autoplay-icon");this.L(m,"click",this.lq);this.api.createClientVe(m,this,115130);this.fP();this.L(n,"autonavvisibility",this.fP);this.L(n,"mdxnowautoplaying",this.eU);this.L(n,"mdxautoplaycanceled",this.nP);g.C(this.element,"ytp-upnext-mobile",this.api.D().j)}A(){this.notification&&(this.Z.stop(),this.N2(this.C),this.C=null,this.notification.close(),
this.notification=null)}Y(n){this.suggestion=n;g.N6(this,n,"hqdefault.jpg")}fP(){this.hF(this.api.hN());this.api.logVisibility(this.element,this.api.hN());this.api.logVisibility(this.m7("ytp-upnext-autoplay-icon"),this.api.hN());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.hN())}cT(){window.focus();this.A()}B(n){this.U()||(g.eX("a11y-announce",`Up Next ${this.suggestion.title}`),this.N=(0,g.l)(),this.j=new g.o9(()=>{BT(this,n)},25),BT(this,n),ZwH(this.api,gaq(this,
n)));
g.Nw(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}U(){return!!this.j}W(){this.X();this.N=(0,g.l)();BT(this);g.wo(this.element,"ytp-upnext-autoplay-paused")}X(){this.U()&&(this.j.dispose(),this.j=null)}select(n=!1){if(this.api.D().O("autonav_notifications")&&n&&window.Notification&&typeof document.hasFocus==="function"){const m=Notification.permission;m==="default"?Notification.requestPermission():m!=="granted"||document.hasFocus()||(this.A(),this.notification=new Notification("Up Next",
{body:this.suggestion.title,icon:this.suggestion.cD()}),this.C=this.L(this.notification,"click",this.cT),this.Z.start())}this.X();this.api.nextVideo(!1,n)}lq(n){!g.CV(this.cancelButton.element,n.target)&&g.ln(n,this.api)&&(this.api.hN()&&this.api.logClick(this.m7("ytp-upnext-autoplay-icon")),this.select())}Uw(){this.api.hN()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.ZV(this.api,!0)}eU(n){this.api.getPresentingPlayerType();this.show();this.B(n)}nP(){this.api.getPresentingPlayerType();
this.X();this.hide()}jU(){this.X();this.A();super.jU()}};var WoY=class extends Ni{constructor(n){super(n,"videowall-endscreen");this.V=n;this.stills=[];this.W=this.videoData=null;this.B=this.Y=!1;this.fP=null;g.wo(this.element,"modern-videowall-endscreen");this.j=new g.Zw(this);g.L(this,this.j);this.A=new g.o9(()=>{g.wo(this.element,"ytp-show-tiles")},0);
g.L(this,this.A);this.table=new g.fD({K:"div",J:"ytp-modern-endscreen-content"});g.L(this,this.table);this.table.Qi(this.element);n.getVideoData().xq?this.U=new yp(n):this.U=new Rfm(n);g.L(this,this.U);g.jn(this.player,this.U.element,4);n.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var n=this.player.getVideoData();n&&(this.videoData=n);this.X();this.j.L(this.player,"appresize",this.X);this.j.L(this.player,"onVideoAreaChange",this.X);this.j.L(this.player,"videodatachange",
this.onVideoDataChange);this.j.L(this.player,"autonavchange",this.N);this.j.L(this.player,"onAutonavCancelled",this.Uw);n=this.videoData.autonavState;n!==this.fP&&this.N(n);this.j.L(this.element,"transitionend",this.lq)}destroy(){this.j.j();g.VX(this.stills);this.stills=[];super.destroy();g.Nw(this.element,"ytp-show-tiles");this.A.stop();this.fP=this.videoData.autonavState}C(){return this.videoData.autonavState!==1}show(){const n=this.Xq;super.show();g.Nw(this.element,"ytp-show-tiles");this.player.D().j?
g.A1(this.A):this.A.start();(this.B||this.W&&this.W!==this.videoData.clientPlaybackNonce)&&g.ZV(this.player,!1);aI(this)?(Vp(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||X$q(this.player.lC())&&this.player.O("web_player_pip_logging_fix")?this.U.select(!0):this.U.B():this.videoData.autonavState===3&&this.U.W()):(g.ZV(this.player,!0),Vp(this));n!==this.Xq&&this.player.logVisibility(this.element,!0)}hide(){const n=this.Xq;super.hide();this.U.W();Vp(this);n!==this.Xq&&this.player.logVisibility(this.element,
!1)}lq(n){n.target===this.element&&this.X()}X(){const n=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.k6()];if(n.length){var m=this.V.nR(!0,this.V.isFullscreen()),M=Math.floor((m.width-64+16)/(g.UO(m.width*.27,250,450)+16));m=Math.min(3,Math.floor((m.height-64)/((m.width-64-(M-1)*16)/M*.5625+70)));g.Qj(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);g.wo(this.element,`ytp-modern-endscreen-limit-rows-${m}`);
g.C(this.element,"ytp-modern-endscreen-single-item",M===1);g.C(this.element,"ytp-modern-endscreen-row-0",m===0);M=this.table.element;M.ariaLive="polite";this.U.Y(this.videoData.k6());this.U instanceof yp&&b_(this.U);g.C(this.element,"ytp-endscreen-takeover",aI(this));Vp(this);m=0;M.ariaBusy="true";var h=n.length;for(let F=0;F<h;F++){const e=F%h;let P=this.stills[F];P||(P=new g.T1P(this.player),this.stills[F]=P,M.appendChild(P.element));g.t8I(P,n[e]);m++}this.stills.length=m}}onVideoDataChange(){const n=
this.player.getVideoData({playerType:1});this.videoData!==n&&(n?.k6()?(this.videoData=n,this.X()):this.player.uq("missg",{vid:n?.videoId||"",cpn:n?.clientPlaybackNonce||""}))}Z(){return this.U.U()}N(n){n===1?(this.B=!1,this.W=this.videoData.clientPlaybackNonce,this.U.X(),this.Xq&&this.X()):(this.B=!0,this.Xq&&aI(this)&&(n===2?this.U.B():n===3&&this.U.W()))}Uw(n){if(n){for(n=0;n<this.stills.length;n++)this.V.logVisibility(this.stills[n].element,!0);this.N(1)}else this.W=null,this.B=!1;this.X()}hN(){return this.Xq&&
aI(this)}};var CJ6=class extends Ni{constructor(n){super(n,"subscribecard-endscreen");this.U=new g.U({K:"div",J:"ytp-subscribe-card",G:[{K:"img",J:"ytp-author-image",S:{src:"{{profilePicture}}"}},{K:"div",J:"ytp-subscribe-card-right",G:[{K:"div",J:"ytp-author-name",PT:"{{author}}"},{K:"div",J:"html5-subscribe-button-container"}]}]});g.L(this,this.U);this.U.Qi(this.element);const m=n.getVideoData();this.subscribeButton=new g.B0("Subscribe",null,"Unsubscribe",null,!0,!1,m.Ha,m.subscribed,"trailer-endscreen",null,
n,!1);g.L(this,this.subscribeButton);this.subscribeButton.Qi(this.U.m7("html5-subscribe-button-container"));this.L(n,"videodatachange",this.oz);this.oz();this.hide()}oz(){const n=this.player.getVideoData();this.U.update({profilePicture:n.profilePicture,author:n.author});this.subscribeButton.channelId=n.Ha;var m=this.subscribeButton;n.subscribed?m.U():m.j()}};var Ko5=class extends g.U{constructor(n){const m=n.D(),M=g.Vg||g.$v?{style:"will-change: opacity"}:void 0,h=m.W,F=["ytp-videowall-still"];m.j&&F.push("ytp-videowall-show-text");super({K:"a",Vi:F,S:{href:"{{url}}",target:h?m.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},G:[{K:"div",J:"ytp-videowall-still-image",S:{style:"{{background}}"}},{K:"span",J:"ytp-videowall-still-info",S:{"aria-hidden":"true"},G:[{K:"span",J:"ytp-videowall-still-info-bg",
G:[{K:"span",J:"ytp-videowall-still-info-content",S:M,G:[{K:"span",J:"ytp-videowall-still-info-title",PT:"{{title}}"},{K:"span",J:"ytp-videowall-still-info-author",PT:"{{author_and_views}}"},{K:"span",J:"ytp-videowall-still-info-live",PT:"Live"},{K:"span",J:"ytp-videowall-still-info-duration",PT:"{{duration}}"}]}]}]},{K:"span",Vi:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],S:{"aria-hidden":"true"},G:[{K:"span",J:"ytp-videowall-still-listlabel-icon"},"Playlist",{K:"span",
J:"ytp-videowall-still-listlabel-length",G:[" (",{K:"span",PT:"{{playlist_length}}"},")"]}]},{K:"span",Vi:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],S:{"aria-hidden":"true"},G:[{K:"span",J:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{K:"span",J:"ytp-videowall-still-listlabel-length",PT:" (50+)"}]}]});this.suggestion=null;this.j=h;this.api=n;this.U=new g.Zw(this);g.L(this,this.U);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.U.L(n,"videodatachange",
this.onVideoDataChange);n.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.GU(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Ga||void 0)&&this.api.logClick(this.element)}onClick(n){if(g.qD(this.api.D())&&this.api.O("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let m=this.suggestion.TA();const M={};g.IF(this.api,M);m=g.CB(m,M);g.qc(m,this.api,n)}else g.ln(n,this.api,
this.j,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(n){switch(n.keyCode){case 13:case 32:n.defaultPrevented||(this.select(),n.preventDefault())}}onVideoDataChange(){const n=this.api.getVideoData(),m=this.api.D();this.j=n.UT?!1:m.W}};var rPY=class extends Ni{constructor(n){super(n,"videowall-endscreen");this.V=n;this.W=0;this.stills=[];this.B=this.videoData=null;this.A=this.fP=!1;this.Uw=null;this.X=new g.Zw(this);g.L(this,this.X);this.N=new g.o9(()=>{g.wo(this.element,"ytp-show-tiles")},0);
g.L(this,this.N);var m=new g.U({K:"button",Vi:["ytp-button","ytp-endscreen-previous"],S:{"aria-label":"Previous"},G:[g.Bl()]});g.L(this,m);m.Qi(this.element);m.listen("click",this.eU,this);this.table=new g.fD({K:"div",J:"ytp-endscreen-content"});g.L(this,this.table);this.table.Qi(this.element);m=new g.U({K:"button",Vi:["ytp-button","ytp-endscreen-next"],S:{"aria-label":"Next"},G:[g.a8()]});g.L(this,m);m.Qi(this.element);m.listen("click",this.BT,this);n.getVideoData().xq?this.U=new yp(n):this.U=new Rfm(n);
g.L(this,this.U);g.jn(this.player,this.U.element,4);n.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var n=this.player.getVideoData();n&&(this.videoData=n);this.j();this.X.L(this.player,"appresize",this.j);this.X.L(this.player,"onVideoAreaChange",this.j);this.X.L(this.player,"videodatachange",this.onVideoDataChange);this.X.L(this.player,"autonavchange",this.Y);this.X.L(this.player,"onAutonavCancelled",this.lq);n=this.videoData.autonavState;n!==this.Uw&&this.Y(n);this.X.L(this.element,
"transitionend",this.nP)}destroy(){this.X.j();g.VX(this.stills);this.stills=[];super.destroy();g.Nw(this.element,"ytp-show-tiles");this.N.stop();this.Uw=this.videoData.autonavState}C(){return this.videoData.autonavState!==1}show(){const n=this.Xq;super.show();g.Nw(this.element,"ytp-show-tiles");this.player.D().j?g.A1(this.N):this.N.start();(this.A||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.ZV(this.player,!1);xo(this)?(wN(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||X$q(this.player.lC())&&this.player.O("web_player_pip_logging_fix")?this.U.select(!0):this.U.B():this.videoData.autonavState===3&&this.U.W()):(g.ZV(this.player,!0),wN(this));n!==this.Xq&&this.player.logVisibility(this.element,!0)}hide(){const n=this.Xq;super.hide();this.U.W();wN(this);n!==this.Xq&&this.player.logVisibility(this.element,!1)}nP(n){n.target===this.element&&this.j()}j(){var n=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.k6()];if(n.length){g.wo(this.element,
"ytp-endscreen-paginate");var m=this.V.nR(!0,this.V.isFullscreen()),M=g.VS(this.V);M&&(M=M.M8()?48:32,m.width-=M*2);var h=m.width/m.height,F=96/54,e=M=2,P=Math.max(m.width/96,2),E=Math.max(m.height/54,2),H=n.length;var z=H*4;for(z-=4;z>0&&(M<P||e<E);){var A=M/2,b=e/2,B=M<=P-2&&z>=b*4,a=e<=E-2&&z>=A*4;if((A+1)/b*F/h>h/(A/(b+1)*F)&&a)z-=A*4,e+=2;else if(B)z-=b*4,M+=2;else if(a)z-=A*4,e+=2;else break}F=!1;z>=12&&H*4-z<=6&&(e>=4||M>=4)&&(F=!0);z=M*96;P=e*54;h=z/P<h?m.height/P:m.width/z;h=Math.min(h,2);
z=Math.floor(Math.min(m.width,z*h));P=Math.floor(Math.min(m.height,P*h));m=this.table.element;m.ariaLive="polite";g.x3(m,z,P);g.mI(m,{marginLeft:`${z/-2}px`,marginTop:`${P/-2}px`});this.U.Y(this.videoData.k6());this.U instanceof yp&&b_(this.U);g.C(this.element,"ytp-endscreen-takeover",xo(this));wN(this);z+=4;P+=4;h=0;m.ariaBusy="true";for(E=0;E<M;E++)for(A=0;A<e;A++)if(B=h,a=0,F&&E>=M-2&&A>=e-2?a=1:A%2===0&&E%2===0&&(A<2&&E<2?A===0&&E===0&&(a=2):a=2),B=g.c6(B+this.W,H),a!==0){b=this.stills[h];b||
(b=new Ko5(this.player),this.stills[h]=b,m.appendChild(b.element));var w=Math.floor(P*A/e);const Z=Math.floor(z*E/M),W=Math.floor(P*(A+a)/e)-w-4,r=Math.floor(z*(E+a)/M)-Z-4;g.zp(b.element,Z,w);g.x3(b.element,r,W);g.mI(b.element,"transitionDelay",(A+E)/20+"s");g.C(b.element,"ytp-videowall-still-mini",a===1);g.C(b.element,"ytp-videowall-still-large",a>2);a=Math.max(r,W);g.C(b.element,"ytp-videowall-still-round-large",a>=256);g.C(b.element,"ytp-videowall-still-round-medium",a>96&&a<256);g.C(b.element,
"ytp-videowall-still-round-small",a<=96);B=n[B];b.suggestion!==B&&(b.suggestion=B,a=b.api.D(),w=g.xT(b.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.N6(b,B,w),g.qD(a)&&!b.api.O("web_player_log_click_before_generating_ve_conversion_params")&&(a=B.TA(),w={},g.Af(b.api,"addEmbedsConversionTrackingParams",[w]),a=g.CB(a,w),b.updateValue("url",a)),(B=(B=B.sessionData)&&B.itct)&&b.api.setTrackingParams(b.element,B));h++}m.ariaBusy="false";g.C(this.element,"ytp-endscreen-paginate",
h<H);for(n=this.stills.length-1;n>=h;n--)M=this.stills[n],g.W3(M.element),g.aA(M);this.stills.length=h}}onVideoDataChange(){const n=this.player.getVideoData({playerType:1});this.videoData!==n&&(n?.k6()?(this.W=0,this.videoData=n,this.j()):this.player.uq("missg",{vid:n?.videoId||"",cpn:n?.clientPlaybackNonce||""}))}BT(){this.W+=this.stills.length;this.j()}eU(){this.W-=this.stills.length;this.j()}Z(){return this.U.U()}Y(n){n===1?(this.A=!1,this.B=this.videoData.clientPlaybackNonce,this.U.X(),this.Xq&&
this.j()):(this.A=!0,this.Xq&&xo(this)&&(n===2?this.U.B():n===3&&this.U.W()))}lq(n){if(n){for(n=0;n<this.stills.length;n++)this.V.logVisibility(this.stills[n].element,!0);this.Y(1)}else this.B=null,this.A=!1;this.j()}hN(){return this.Xq&&xo(this)}};var doH=class extends g.U{constructor(n){super({K:"button",Vi:["ytp-watch-on-youtube-button","ytp-button"],PT:"{{content}}"});this.V=n;this.buttonType=this.buttonType=1;this.U();this.buttonType===2&&g.wo(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.U);this.hF(!0)}U(){let n,m;switch(this.buttonType){case 1:n="Watch again on YouTube";m=156915;break;case 2:n="Continue watching on YouTube";m=156942;break;default:n="Continue watching on YouTube",
m=156942}this.update({content:n});this.V.hasVe(this.element)&&this.V.destroyVe(this.element);this.V.createClientVe(this.element,this,m)}onClick(n){this.V.O("web_player_log_click_before_generating_ve_conversion_params")&&this.V.logClick(this.element);g.qc(this.getVideoUrl(),this.V,n);this.V.O("web_player_log_click_before_generating_ve_conversion_params")||this.V.logClick(this.element)}getVideoUrl(){var n=!0;switch(this.buttonType){case 1:n=!0;break;case 2:n=!1}n=this.V.getVideoUrl(n,!1,!1,!0);const m=
this.V.D();if(g.qD(m)){const M={};g.qD(m)&&g.Af(this.V,"addEmbedsConversionTrackingParams",[M]);n=g.CB(n,M)}return n}logVisibility(){this.V.logVisibility(this.element,this.Xq&&this.k6)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}Xf(n){super.Xf(n);this.logVisibility()}};var Doq=class extends Ni{constructor(n){super(n,"watch-again-on-youtube-endscreen");this.watchButton=new doH(n);g.L(this,this.watchButton);this.watchButton.Qi(this.element);g.fCN(n)&&(this.U=new g.ImH(n),g.L(this,this.U),this.j=new g.U({K:"div",Vi:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],S:{tabIndex:"-1"},G:[this.U]}),g.L(this,this.j),this.U.Qi(this.j.element),this.j.Qi(this.element));n.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.U?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();const m=this.j;if(m){var n=this.U.hasSuggestions();g.C(this.element,"ytp-shorts-branded-ui",n);n?m.show():m.hide()}g.VS(this.player)?.D$(!0);this.player.logVisibility(this.element,!0);this.watchButton.Xf(!0)}}hide(){super.hide();g.VS(this.player)?.D$(!1);this.player.logVisibility(this.element,!1);this.watchButton.Xf(!1)}};g.K0("endscreen",class extends g.fn{constructor(n){super(n);this.endScreen=null;this.U=this.j=!1;this.listeners=new g.Zw(this);g.L(this,this.listeners);const m=n.D();n.isEmbedsShortsMode()?this.endScreen=new Doq(n):IWo(n)?(this.j=!0,$o7(this),m.O("delhi_modern_endscreen")?this.endScreen=new WoY(n):this.endScreen=new rPY(n)):m.JN?this.endScreen=new CJ6(n):this.endScreen=new Ni(n);g.L(this,this.endScreen);g.jn(n,this.endScreen.element,4);jc6(this);this.listeners.L(n,"videodatachange",this.onVideoDataChange,
this);this.listeners.L(n,g.jK("endscreen"),M=>{this.onCueRangeEnter(M)});
this.listeners.L(n,g.RE("endscreen"),M=>{this.onCueRangeExit(M)})}Rb(){var n=this.player.getVideoData();
const m=n.mutedAutoplay&&(n.limitedPlaybackDurationInSeconds>0||n.endSeconds>0||n.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!m)return!0;var M=!(!n?.k6()&&!n?.suggestions?.length);M=!IWo(this.player)||M;n=n.Rj;const h=this.player.je();return M&&!n&&!h&&!m}hN(){return this.endScreen.hN()}RW(){return this.hN()?this.endScreen.Z():!1}jU(){this.player.Aj("endscreen");super.jU()}load(){{const M=this.player.getVideoData(),h=M.transitionEndpointAtEndOfStream;if(h&&h.videoId){var n=
this.player.ef().nw.get("heartbeat");var m=M.k6();!m||h.videoId!==m.videoId||M.oy?(this.player.GU(h.videoId,void 0,void 0,!0,!0,h),n&&n.zH("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),n=!0):n=!1}else n=!1}n||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(n){this.Rb()&&(this.endScreen.created||this.endScreen.create(),n.getId()==="load"&&this.load())}onCueRangeExit(n){n.getId()===
"load"&&this.loaded&&this.unload()}onVideoDataChange(){jc6(this);this.j&&$o7(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.endScreen=new rPY(this.player),g.L(this,this.endScreen),g.jn(this.player,this.endScreen.element,4))}});})(_yt_player);
