(function(g){var window=this;'use strict';var xhH=function(n,m,M){g.O(function(h){n.j=g.aX(m,M);h.N()})},WT=function(n){n.isActive()||n.start()},wUS=function(n,m){var M=new g.VF;
M.languageCode=n.languageCode;M.languageName=n.languageName;M.name=n.name;M.displayName=n.displayName;M.kind=n.kind;M.isDefault=!1;M.U=n.U;M.isTranslateable=n.isTranslateable;M.vssId=n.vssId;M.url=n.url;M.translationLanguage=m;n.xtags&&(M.xtags=n.xtags);n.captionId&&(M.captionId=n.captionId);return M},y97=function(n,m){return m?n.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},NOq=function(n){return g.el(n)||n.J("web_enable_caption_language_preference_stickiness")},Y5P=function(n,m){var M,
h,F;
return g.O(function(e){if(e.j==1)return M=n+"|"+m,e.U(g.OD(),2);if(e.j!=3){h=e.X;if(!h)throw g.H7("gct");return e.U(g.g9(h),3)}F=e.X;return e.return(F.get("captions",M))})},Q26=function(n,m,M){Y5P(n,m).then(function(h){h&&M(h.trackData,new g.VF(h.metadata))})},L3K=function(n){if(!ZBV.test(n))throw Error("'"+n+"' is not a valid hex color");
n.length==4&&(n=n.replace(XUw,"#$1$1$2$2$3$3"));n=n.toLowerCase();n=parseInt(n.slice(1),16);return[n>>16,n>>8&255,n&255]},gw5=function(){var n=void 0;
n=n===void 0?{}:n;var m="suggest_correction"in g.GS_?g.GS_.suggest_correction:"Edit caption";m=m||"";var M={},h;for(h in n){M={NZ:M.NZ};M.NZ=h;var F=function(e){return function(){return String(n[e.NZ])}}(M);
m=m.replace(new RegExp("\\$\\{"+M.NZ+"\\}","gi"),F);m=m.replace(new RegExp("\\$"+M.NZ,"gi"),F)}return m},Idq=function(){return g.Ij("yt-player-caption-display-settings")},$hY=function(n){g.rX.call(this,n);
this.j=new Set},CZ=function(){this.segments=[]},j2P=function(n,m){var M=g.j5(n.segments,m);
M>=0||M<0&&(-M-1)%2===1||(M=-M-1,M>0&&m-n.segments[M-1]===1&&M<n.segments.length&&n.segments[M]-m===1?(g.VV(n.segments,M),g.VV(n.segments,M-1)):M>0&&m-n.segments[M-1]===1?n.segments[M-1]=m:M<n.segments.length&&n.segments[M]-m===1?n.segments[M]=m:(g.gS(n.segments,M,0,m),g.gS(n.segments,M+1,0,m)))},RZY=function(n,m,M,h,F,e){g.p.call(this);
this.policy=n;this.player=m;this.X6=M;this.G=h;this.B=F;this.k6=e;this.W=new CZ;this.N=-1;this.j=this.X=this.U=null;this.fP=0;this.C=new g.Rd(this.dV,1E3,this);this.events=new g.KH(this);g.f(this,this.C);g.f(this,this.events);this.events.D(m,"SEEK_COMPLETE",this.Kt);this.Kt();this.dV()},W3P=function(n){return n.U&&n.U.B?n.U.B+n.player.gL()<n.player.getCurrentTime():!1},C8H=function(n,m){if(n.policy.t8&&n.player.xa()){var M=g.nu(m,n.policy,{});
M.set("pot",n.player.xa());M=M.R9()}else M=g.nu(m,n.policy,{}).R9();var h={format:"RAW",withCredentials:!0};if(n.policy.Ow){h.method="POST";var F=m.W;F&&Object.keys(F).length>0?h.postBody=g.bl(F,g.qm):h.postBody=(0,g.at)([120,0])}n.B&&(h.responseType="arraybuffer");var e=++n.fP,P=(0,g.Vn)();n.j=g.yu(M,h,3,100,-1,function(H){H.errorCode==="net.timeout"&&n.player.uq("capnt",{rn:e++})}).then(function(H){if(n.policy.ZNU&&e%100===1){var z=(0,g.Vn)();
n.player.uq("caprsp",{rn:e,ms:z-P,kb:(H.xhr.responseText.length/1024).toFixed()})}a:{H=H.xhr;n.F6();if(n.X){var A=!(n.B?H.response:H.responseText)||H.status>=400;if(z=g.v9m(H)){H=g.nu(n.X,n.policy,{});n.X.KR(H,z);C8H(n,n.X);break a}if(A)n.player.uq("capfail",{status:H.status});else{var b;g.n2("fcb_r",(0,g.Vn)(),((b=n.player.getVideoData())==null?void 0:b.G)||"");b=n.X.pP[0];z=b.x6;n.G!=null&&n.N!==z&&(n.B?n.G(H.response,(b.startTime+n.player.gL())*1E3):n.G(H.responseText,(b.startTime+n.player.gL())*
1E3),n.N=z)}}n.X=null;n.j=null}}).Wl(function(H){n.X=null;
n.j=null;var z;n.player.uq("capfail",{rn:e,status:(z=H.xhr)==null?void 0:z.status})});
n.X=m;j2P(n.W,n.X.pP[0].x6)},KZ=function(n,m){g.rX.call(this,m);
this.j=n;this.V=m;this.W=null;this.N=!1;this.logger=new g.z_("caps");this.C=g.$BU(this.V,this.j)},r9w=function(n,m){var M=[],h;
for(h in n.j.U)if(n.j.U.hasOwnProperty(h)){var F=n.j.U[h];if(g.Dh(F,m||null)){var e=F.info.id,P=e,H="."+e,z="",A="";if(F=F.info.captionTrack)e=F.languageCode,P=F.displayName,H=F.vssId,z=F.kind,A=F.id;else{F=e;var b=g.xlS.get(F);b==null&&(b=K35[F]||K35[F.replace(/-/g,"_")],g.xlS.set(F,b));F=b;P=F||P}M.push(new g.VF({id:h,languageCode:e,languageName:P,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:H,kind:z,captionId:A}))}}return M},dhP=function(n,m){return m!=null&&m in n.j.U?n.j.U[m]:null},
DhK=function(n,m,M){var h=[],F;
for(F in n.j.U)if(n.j.U.hasOwnProperty(F)){var e=n.j.U[F];if(g.Dh(e,M||null)){var P=e.info.captionTrack;P&&P.languageCode===m&&h.push(e)}}return h.length?h[0]:null},rN=function(n,m,M,h,F,e,P,H,z,A){var b=A.isInline()&&!0,B={};
Object.assign(B,m);Object.assign(B,n.params);Object.assign(B,M);var V={};Object.assign(V,m.iI);n.params.iI&&Object.assign(V,n.params.iI);Object.assign(V,M.iI);b&&(B.windowOpacity=.6,V.backgroundOpacity=0);B.iI=V;var a=B.qP===1,x=[{K:"span",L:"captions-text",Y:{style:"word-wrap: normal; display: block;"}}],Y,X,N,C=H.D9("caption_edit_on_hover")&&((Y=A.getVideoData().getPlayerResponse())==null?void 0:(X=Y.captions)==null?void 0:(N=X.playerCaptionsTracklistRenderer)==null?void 0:N.openTranscriptCommand);
C&&x.unshift({K:"button",L:"caption-edit",Y:{tabindex:"0","aria-label":gw5()},Z:[{K:"svg",Y:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},Z:[{K:"path",Y:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.T.call(this,{K:"div",L:"caption-window",Y:{id:"caption-window-"+n.id,dir:a?"rtl":"ltr",tabindex:"0",lang:B.lang},Z:x});var K=
this;this.N=[];this.Iz=!1;this.j=n;this.Ow=this.Vi=null;this.VC=e;this.e$=P;this.C=null;this.maxWidth=e*.96;this.maxHeight=P*.96;this.U=B;this.BA=M;this.lq=m;this.X=this.m7("captions-text");this.U9=this.X.style.getPropertyValue("box-decoration-break")!==""||this.X.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.zv=S5q(h,F,e,P);this.a$=z;C&&(this.B=this.m7("caption-edit"),this.D(this.B,"click",function(){K.a$()}));
this.type=0;this.dW=this.zv*tQ6(V);this.Xq=b;this.HT=H.D9("enable_centered_caption_for_tvfilm_video")&&A.getVideoData().isTvfilmVideo;this.G=A.S().Gv().U.oz(g.uGH);n=new g.kF(this.element,!0);g.f(this,n);n.subscribe("dragstart",this.s8,this);n.subscribe("dragmove",this.gH,this);n.subscribe("dragend",this.RN,this);this.rL=this.SU=this.Ua=this.kq=0;n="";this.U.windowOpacity&&(n=L3K(this.U.windowColor),n="rgba("+n[0]+","+n[1]+","+n[2]+","+this.U.windowOpacity+")");m={"background-color":n,display:this.U.isVisible===
!1?"none":"","text-align":OBS[this.U.textAlign]};this.U9&&(m["border-radius"]=n?this.dW/8+"px":"");(this.W=this.j.params.qP===2||this.j.params.qP===3)&&pUV(this,this.element);g.W3(this.element,m);if(b){var d;(d=this.element.parentElement)==null||d.style.setProperty("--caption-window-color",n)}switch(this.U.kM){case 0:case 1:case 2:g.pR(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.pR(this.element,"ytp-caption-window-bottom")}},pUV=function(n,m){var M="vertical-rl";
n.U.RT===1&&(M="vertical-lr");g.Jd&&(M=M==="vertical-lr"?"tb-lr":"tb-rl");g.W3(m,"-o-writing-mode",M);g.W3(m,"-webkit-writing-mode",M);g.W3(m,"writing-mode",M);g.W3(m,"text-orientation","upright");g.pR(m,"ytp-vertical-caption");n.j.params.qP===3&&(g.W3(m,"text-orientation",""),g.W3(m,"transform","rotate(180deg)"))},tQ6=function(n){var m=1+.25*(n.fontSizeIncrement||0);
if(n.offset===0||n.offset===2)m*=.8;return m},fdH=function(n,m){var M={},h=m.background?m.background:n.U.iI.background;
if(m.backgroundOpacity!=null||m.background){var F=m.backgroundOpacity!=null?m.backgroundOpacity:n.U.iI.backgroundOpacity;h=L3K(h);M.background="rgba("+h[0]+","+h[1]+","+h[2]+","+F+")";n.U9&&(M["box-decoration-break"]="clone",M["border-radius"]=n.dW/8+"px")}if(m.fontSizeIncrement!=null||m.offset!=null)M["font-size"]=n.zv*tQ6(m)+"px";h=1;F=m.color||n.U.iI.color;if(m.color||m.textOpacity!=null)F=L3K(F),h=m.textOpacity==null?n.U.iI.textOpacity:m.textOpacity,F="rgba("+F[0]+","+F[1]+","+F[2]+","+h+")",
M.color=F,M.fill=F;var e=m.charEdgeStyle;e===0&&(e=void 0);if(e){F="rgba(34, 34, 34, "+h+")";var P="rgba(204, 204, 204, "+h+")";m.XW&&(P=F=m.XW);var H=n.zv/16/2,z=Math.max(H,1),A=Math.max(2*H,1),b=Math.max(3*H,1),B=Math.max(5*H,1);h=[];switch(e){case 4:for(;b<=B;b+=H)h.push(A+"px "+A+"px "+b+"px "+F);break;case 1:A=window.devicePixelRatio>=2?.5:1;for(e=z;e<=b;e+=A)h.push(e+"px "+e+"px "+F);break;case 2:h.push(z+"px "+z+"px "+P);h.push("-"+z+"px -"+z+"px "+F);break;case 3:for(b=0;b<5;b++)h.push("0 0 "+
A+"px "+F)}M["text-shadow"]=h.join(", ")}F="";switch(m.fontFamily){case 1:F='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:F='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:F='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:F='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:F='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:F=g.dK()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:F='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}F&&(M["font-family"]=F);F=m.offset;F==null&&(F=n.U.iI.offset);switch(F){case 0:M["vertical-align"]="sub";break;case 2:M["vertical-align"]="super"}m.fontFamily===7&&(M["font-variant"]="small-caps");m.bold&&(M["font-weight"]="bold");m.italic&&(M["font-style"]="italic");m.underline&&(M["text-decoration"]=
"underline");m.jps&&(M.visibility="hidden");m.yz===1&&n.W&&(M["text-combine-upright"]="all",M["text-orientation"]="mixed",F=g.UP||g.P7,n.j.params.qP===3?M.transform=F?"rotate(90deg)":"rotate(180deg)":F&&(M.transform="rotate(-90deg)"));if(m.textEmphasis===1||m.textEmphasis===2||m.textEmphasis===3||m.textEmphasis===4||m.textEmphasis===5)if(g.UP)M["font-weight"]="bold";else switch(M["text-emphasis-style"]="filled circle",M["text-emphasis-color"]="currentcolor",M["webkit-text-emphasis"]="filled circle",
m.textEmphasis){case 4:case 3:M["text-emphasis-position"]="under left";M["webkit-text-emphasis-position"]="under left";break;case 5:case 2:M["text-emphasis-position"]="over right",M["webkit-text-emphasis-position"]="over right"}return M},dN=function(n){n=n.split("px");
return n.length>0?(n=Number(n[0]))?n:0:0},vwS=function(n){n.C=g.hs("SPAN");
g.W3(n.C,{display:"block"});g.pR(n.C,"caption-visual-line");n.X.appendChild(n.C)},ldH=function(n,m){var M=g.hs("SPAN");
g.W3(M,{display:"inline-block","white-space":"pre-wrap"});g.W3(M,fdH(n,m));M.classList.add("ytp-caption-segment");n.C.appendChild(M);M.previousElementSibling&&(g.W3(M.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.W3(M,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return M},q5o=function(n,m,M){n.Iz=n.Iz||!!M;
var h={};Object.assign(h,n.U.iI);Object.assign(h,M||m.U);Object.assign(h,n.BA.iI);(M=!n.C)&&vwS(n);for(var F=n.Vi&&n.Ow&&g.ha(h,n.Ow)?n.Vi:ldH(n,h),e=typeof m.text==="string",P=e?m.text.split("\n"):[m.text],H=0;H<P.length;H++){var z=H>0||!m.append,A=P[H];z&&!M?(vwS(n),F=ldH(n,h)):z&&M&&(M=!1);A&&(F.appendChild(e?g.FG(A):A),e||A.tagName!=="RUBY"||A.childElementCount!==4||g.UP||!g.KV(A.children[2],"text-emphasis")||(z=n.W?"padding-right":"padding-top",g.KV(A.children[2],"text-emphasis-position")&&(z=
n.W?"padding-left":"padding-bottom"),g.uo?g.W3(F,z,"1em"):g.W3(F,z,"0.5em")))}n.Ow=h;n.Vi=F;n.N.push(m)},S5q=function(n,m,M,h){var F=m/360*16;
m>=n&&(n=640,h>M*1.3&&(n=480),F=M/n*16);return F},GRm=function(){this.X=this.time=this.mode=this.j=0;
this.W=new TO_(this);this.B=new TO_(this);this.U=[];this.clear()},J9H=function(n,m,M){if(n===255&&m===255||!n&&!m)return{mf:n,
KX:m,result:0};n=kRw[n];m=kRw[m];if(n&128){var h;if(h=!(m&128))h=m,h=M.Jj()&&M.KX===h;if(h)return{mf:n,KX:m,result:1}}else if(m&128&&1<=n&&n<=31)return{mf:n,KX:m,result:2};return{mf:n,KX:m,result:3}},c9S=function(n,m,M,h){m===255&&M===255||!m&&!M?(++n.X===45&&n.reset(),n.W.j.clear(),n.B.j.clear()):(n.X=0,UhV(n.W,m,M,h))},s2_=function(n,m){n.U.sort(function(F,e){var P=F.time-e.time;
return P===0?F.order-e.order:P});
for(var M=g.Q(n.U),h=M.next();!h.done;h=M.next())h=h.value,n.time=h.time,h.type===0?c9S(n,h.Jx,h.CZ,m):h.type===1&&n.j&496&&UhV(n.B,h.Jx,h.CZ,m);n.U.length=0},Dx=function(){this.type=0},SE=function(){this.state=this.KX=this.mf=0},uB6=function(){this.timestamp=this.U=0},tv=function(n){this.B=n;
this.X=[];this.U=this.j=this.row=0;this.style=new Dx;for(n=this.W=0;n<=15;n++){this.X[n]=[];for(var m=0;m<=32;m++)this.X[n][m]=new uB6}},O6=function(n,m){if(n.style.type===3){for(var M=0,h=0,F=n.B.time+0,e="",P="",H=F,z=1;z<=15;++z){for(var A=!1,b=h?h:1;b<=32;++b){var B=n.X[z][b];
if(B.U!==0){M===0&&(M=z,h=b);A=String.fromCharCode(B.U);var V=B.timestamp;V<F&&(F=V);B.timestamp=H;P&&(e+=P,P="");e+=A;A=!0}if((B.U===0||b===32)&&A){P="\n";break}else if(h&&!A)break}if(M&&!A)break}e&&m.W(M,h,F,H,e)}else for(h=M=0,e=F=n.B.time+0,P=1;P<=15;++P)for(H="",z=1;z<=32;++z)if(b=n.X[P][z],B=b.U,B!==0&&(M===0&&(M=P,h=z),A=String.fromCharCode(B),V=b.timestamp,V<=F&&(F=V),H+=A,b.reset()),z===32||B===0)H&&m.W(M,h,F,e,H),F=e,H="",h=M=0},F4H=function(n,m){switch(n){case 0:return nC_[(m&127)-32];
case 1:return mQw[m&15];case 2:return MoS[m&31];case 3:return hO7[m&31]}return 0},pZ=function(n){return n.X[n.row][n.j]},fZ=function(n,m,M){m>=2&&n.j>1&&(--n.j,pZ(n).U=0);
var h=pZ(n);h.timestamp=n.B.time+0;h.U=F4H(m,M);n.j<32&&n.j++},ieH=function(n,m,M,h){for(var F=0;F<h;F++)for(var e=0;e<=32;e++){var P=n.X[m+F][e],H=n.X[M+F][e];
P.U=H.U;P.timestamp=H.timestamp}},vT=function(n,m,M){for(var h=0;h<M;h++)for(var F=0;F<=32;F++)n.X[m+h][F].reset()},eOS=function(n){n.row=n.U>0?n.U:1;
n.j=1;vT(n,0,15)},PvS=function(n){this.X=n;
this.B=0;this.style=new Dx;this.N=new tv(this.X);this.C=new tv(this.X);this.text=new tv(this.X);this.j=this.N;this.W=this.C;this.U=this.j},ECK=function(n,m,M){var h=n.j,F=!1;
switch(n.style.get()){case 4:case 1:case 2:n.style.get()===4&&h.U>0||(O6(h,M),eOS(n.j),eOS(n.W),h.row=15,h.U=m,F=!0)}n.style.set(3);n.U=h;n.U.style=n.style;n.X.mode=1<<h.W;F?h.j=1:h.U!==m&&(h.U>m?(O6(h,M),vT(h,h.row-h.U,m)):h.row<m&&(m=h.U),h.U=m)},He5=function(n){n.style.set(1);
n.U=n.W;n.U.U=0;n.U.style=n.style;n.X.mode=1<<n.U.W},zO_=function(n){n.style.set(4);
n.U=n.text;n.U.style=n.style;n.X.mode=1<<n.U.W},TO_=function(n){this.U=n;
this.B=0;this.X=new PvS(this.U);this.N=new PvS(this.U);this.j=new SE;this.W=this.X},UhV=function(n,m,M,h){n.j.update();
m=J9H(m,M,n.j);switch(m.result){case 0:return;case 1:case 2:return}var F=m.mf;M=m.KX;if(32<=F||!F)n.U.mode&n.U.j&&(m=F,m&128&&(m=127),M&128&&(M=127),n=n.W.U,m&96&&fZ(n,0,m),M&96&&fZ(n,0,M),m!==0&&M!==0&&n.style.type===3&&O6(n,h));else if(F&16)a:if(!n.j.matches(F,M)&&(m=n.j,m.mf=F,m.KX=M,m.state=2,m=F&8?n.N:n.X,n.W=m,n.U.mode=1<<(n.B<<2)+(m.B<<1)+(m.style.type===4?1:0),(n.U.mode|1<<(n.B<<2)+(m.B<<1)+(m.style.type!==4?1:0))&n.U.j))if(M&64){h=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(F&7)<<1|M>>5&1];
n=M&16?((M&14)>>1)*4:0;M=m.U;switch(m.style.get()){case 4:h=M.row;break;case 3:if(h!==M.row){if(h<M.U&&(h=M.U,h===M.row))break;var e=1+M.row-M.U,P=1+h-M.U;ieH(M,P,e,M.U);m=e;F=M.U;P<e?(e=P+F-e,e>0&&(m+=e,F-=e)):(e=e+F-P,e>0&&(F-=e));vT(M,m,F)}}M.row=h;M.j=n+1}else switch(F&7){case 1:switch(M&112){case 32:fZ(m.U,0,32);break a;case 48:M===57?(h=m.U,pZ(h).U=0,h.j<32&&h.j++):fZ(m.U,1,M&15)}break;case 2:M&32&&fZ(m.U,2,M&31);break;case 3:M&32&&fZ(m.U,3,M&31);break;case 4:case 5:if(32<=M&&M<=47)switch(M){case 32:He5(m);
break;case 33:h=m.U;h.j>1&&(--h.j,pZ(h).U=0);break;case 36:h=m.U;m=pZ(h);for(n=0;n<=15;n++)for(M=0;M<=32;M++)if(h.X[n][M]===m){for(;M<=32;M++)h.X[n][M].reset();break}break;case 37:ECK(m,2,h);break;case 38:ECK(m,3,h);break;case 39:ECK(m,4,h);break;case 40:fZ(m.U,0,32);break;case 41:m.style.set(2);m.U=m.j;m.U.U=0;m.U.style=m.style;m.X.mode=1<<m.U.W;break;case 42:h=m.text;h.U=15;h.style.set(4);eOS(h);zO_(m);break;case 43:zO_(m);break;case 44:n=m.j;switch(m.style.get()){case 1:case 2:case 3:O6(n,h)}vT(n,
0,15);break;case 45:b:{n=m.U;switch(m.style.get()){default:case 2:case 1:break b;case 4:if(n.row<15){++n.row;n.j=1;break b}break;case 3:}n.U<2&&(n.U=2,n.row<n.U&&(n.row=n.U));m=n.row-n.U+1;O6(n,h);ieH(n,m,m+1,n.U-1);vT(n,n.row,1)}break;case 46:vT(m.W,0,15);break;case 47:O6(m.j,h),m.W.updateTime(m.X.time+0),h=m.W,m.W=m.j,m.j=h,He5(m)}break;case 7:switch(M){case 33:case 34:case 35:h=m.U,(h.j+=M&3)>32&&(h.j=32)}}},oCq=function(){},l_=function(n,m,M,h,F,e,P){e=e===void 0?!1:e;
P=P===void 0?null:P;g.E4.call(this,n,n+m,{priority:M,namespace:"captions"});this.windowId=h;this.text=F;this.append=e;this.U=P},beS=function(n,m,M,h,F,e,P){var H=e[0],z=P[H.getAttribute("p")];
if(z.jc===1){var A=e[1],b=e[2];e=e[3];H.getAttribute("t");A.getAttribute("t");b.getAttribute("t");e.getAttribute("t");H.getAttribute("p");A.getAttribute("p");e.getAttribute("p");P=P[b.getAttribute("p")];H=Auw(H.textContent,A.textContent,b.textContent,e.textContent,P);return new l_(n,m,F,M,H,h,z)}switch(z.jc){case 9:case 10:z.textEmphasis=1;break;case 11:z.textEmphasis=2;break;case 12:z.textEmphasis=3;break;case 13:z.textEmphasis=4;break;case 14:z.textEmphasis=5}return new l_(n,m,F,M,H.textContent||
"",h,z)},Auw=function(n,m,M,h,F){var e=g.dK(),P=e?g.hs("DIV"):g.hs("RUBY"),H=g.hs("SPAN");
H.textContent=n;P.appendChild(H);n=e?g.hs("DIV"):g.hs("RP");n.textContent=m;P.appendChild(n);m=e?g.hs("DIV"):g.hs("RT");m.textContent=M;P.appendChild(m);M=F.jc;if(M===10||M===11||M===12||M===13||M===14)if(g.W3(m,"text-emphasis-style","filled circle"),g.W3(m,"text-emphasis-color","currentcolor"),g.W3(m,"webkit-text-emphasis","filled circle"),F.jc===11||F.jc===13)g.W3(m,"webkit-text-emphasis-position","under left"),g.W3(m,"text-emphasis-position","under left");M=!0;if(F.jc===4||F.jc===7||F.jc===12||
F.jc===14)g.W3(P,"ruby-position","over"),g.W3(P,"-webkit-ruby-position","before");else if(F.jc===5||F.jc===6||F.jc===11||F.jc===13)g.W3(P,"ruby-position","under"),g.W3(P,"-webkit-ruby-position","after"),M=!1;F=e?g.hs("DIV"):g.hs("RP");F.textContent=h;P.appendChild(F);e&&(h=M,g.W3(P,{display:"inline-block",position:"relative"}),e=P.firstElementChild.nextElementSibling,g.W3(e,"display","none"),e=e.nextElementSibling,g.W3(e,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.W3(P.lastElementChild,"display","none"),h?(g.W3(P,"padding-top","0.6em"),g.W3(e,"top","0")):(g.W3(P,"padding-bottom","0.6em"),g.W3(e,"bottom","0")));return P},qi=function(){g.p.apply(this,arguments)},Te=function(n,m,M,h,F){g.E4.call(this,n,n+m,{priority:M,
namespace:"captions"});this.id=h;this.params=F;this.U=[]},Bd7=function(n){var m="_"+Ge++;
return new Te(0,0x8000000000000,0,m,n)},ko=function(n){qi.call(this);
this.W=n;this.pens={};this.G={};this.k6={};this.B="_"+Ge++;this.C={};this.j=this.U=null;this.N=!0},Jv=function(n,m){n=n.getAttribute(m);
if(n!=null)return Number(n)},U6=function(n,m){n=n.getAttribute(m);
if(n!=null)return n==="1"},cT=function(n,m){n=Jv(n,m);
return n!==void 0?n:null},u_=function(n,m){n=n.getAttribute(m);
if(n!=null)return s6.test(n),n},ajS=function(n,m){var M={},h=m.getAttribute("ws");
Object.assign(M,h?n.k6[h]:n.W);n=cT(m,"mh");n!=null&&(M.XN=n);n=cT(m,"ju");n!=null&&(M.textAlign=n);n=cT(m,"pd");n!=null&&(M.qP=n);n=cT(m,"sd");n!=null&&(M.RT=n);n=u_(m,"wfc");n!=null&&(M.windowColor=n);m=Jv(m,"wfo");m!==void 0&&(M.windowOpacity=m/255);return M},Vow=function(n,m){var M={},h=m.getAttribute("wp");
h&&Object.assign(M,n.G[h]);n=cT(m,"ap");n!=null&&(M.kM=n);n=Jv(m,"cc");n!=null&&(M.Fx=n);n=Jv(m,"ah");n!=null&&(M.zt=n);n=Jv(m,"rc");n!=null&&(M.b8=n);m=Jv(m,"av");m!=null&&(M.Eb=m);return M},xQ_=function(n,m,M,h){var F={};
Object.assign(F,Vow(n,m));Object.assign(F,ajS(n,m));h?g.ha(F,n.W)?(h=n.B,F=n.W):h="_"+Ge++:h=m.getAttribute("id")||"_"+Ge++;n=Jv(m,"t")+M;m=Jv(m,"d")||0x8000000000000;if(F.qP===2||F.qP===3)M=F.b8,F.b8=F.Fx,F.Fx=M;return new Te(n,m,0,h,F)},nI=function(n){qi.call(this);
this.N=n;this.U=new Map;this.W=new Map;this.B=new Map;this.j=new Map},m9=function(n){n=g.W6(Math.round(n),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-n.length)+n},wWV=function(n,m,M,h,F){h===0&&(h=0x8000000000000);
var e={};m.wpWinPosId&&Object.assign(e,n.W.get(m.wpWinPosId));m.wsWinStyleId&&Object.assign(e,n.B.get(m.wsWinStyleId));n=m.rcRowCount;n!==void 0&&(e.b8=n);m=m.ccColCount;m!==void 0&&(e.Fx=m);if(e.qP===2||e.qP===3)m=e.b8,e.b8=e.Fx,e.Fx=m;return new Te(M,h,0,F,e)},Ms=function(n,m,M){g.rX.call(this,n);
this.videoData=m;this.audioTrack=M;this.B=m.Yo},hA=function(n,m,M,h,F,e,P,H,z,A){rN.call(this,n,m,M,h,F,e,P,H,z,A);
this.type=1},Fq=function(n,m,M){this.trackData=n;
this.N=M;this.version=this.B=this.X=this.byteOffset=0;this.j=[];this.U=new DataView(this.trackData)},iY=function(n){var m=n.byteOffset;
n.byteOffset+=1;return n.U.getUint8(m)},eW=function(n){var m=n.byteOffset;
n.byteOffset+=4;return n.U.getUint32(m)},Pb=function(n,m){qi.call(this);
this.j=n;this.W=m;this.track=this.W.languageName==="CC3"?4:0;this.U=new GRm;this.U.j=1<<this.track},Ndw=function(n){if(typeof n==="string")return!1;
n=new Fq(n,8,0);return yu6(n)},yu6=function(n){if(!(n.byteOffset<n.U.byteLength)||eW(n)!==1380139777)return!1;
n.version=iY(n);if(n.version>1)return!1;iY(n);iY(n);iY(n);return!0},ET=function(n,m,M,h,F,e,P,H,z,A){rN.call(this,n,m,M,h,F,e,P,H,z,A);
var b=this;this.type=2;this.eU=[];this.Uw=this.fP=this.vT=0;this.BT=NaN;this.nY=0;this.cA=null;this.CY=new g.Rd(this.T0,433,this);this.B&&(A.createClientVe(this.B,this,167342),this.D(this.B,"click",function(){A.logClick(b.B)}),n=new g.kF(this.element,!0),g.f(this,n),n.subscribe("hoverstart",function(){A.logVisibility(b.B,!0)},this));
g.pR(this.element,"ytp-caption-window-rollup");g.f(this,this.CY);g.W3(this.element,"overflow","hidden")},YLV=function(n,m){if(!m)return"";
n.W&&n.j.params.RT!==1&&(m*=-1);return"translate"+(n.W?"X":"Y")+"("+m+"px)"},QA5=function(n){n.eU=Array.from(n.element.getElementsByClassName("caption-visual-line"));
for(var m=n.j.params.b8,M=0,h=0,F=n.eU.length-1;M<m&&F>-1;){var e=n.eU[F];h+=n.W?e.offsetWidth:e.offsetHeight;M++;F--}n.fP=h;m=Math;M=m.max;isNaN(n.BT)&&((h=n.U.Fx)?(F=g.hs("SPAN"),g.zl(F,"\u2013".repeat(h)),g.W3(F,fdH(n,n.U.iI)),n.X.appendChild(F),n.BT=F.offsetWidth,n.X.removeChild(F)):n.BT=0);h=n.X;n.Uw=M.call(m,n.BT,n.nY,(n.W?h.offsetHeight:h.offsetWidth)+1)},Ze_=function(n,m){QA5(n);
var M=n.eU.reduce(function(e,P){return(n.W?P.offsetWidth:P.offsetHeight)+e},0);
M=n.fP-M;if(M!==n.vT){var h=M>0&&n.vT===0,F=M<n.vT;m||isNaN(M)||h||!F||(g.pR(n.element,"ytp-rollup-mode"),n.D(n.element,"transitionend",n.T0));g.W3(n.X,"transform",YLV(n,M));n.vT=M}QA5(n)},XWV=function(n,m,M,h){var F=this;
this.V=n;this.B=m;this.logger=M;this.xq=h;this.vA=[];this.U=null;this.X=[];this.vL=[];this.j=null;this.Sf={WX6:function(){return F.j},
lm:function(){return F.vA},
E$u:function(e){F.X=e},
nZ6:function(){return F.X}};
n=g.Aq(this.V.S().experiments,"html5_override_micro_discontinuities_threshold_ms");this.W=n>0?n:10},$QK=function(n,m){n.j=function(M,h){if(n.V.S().experiments.D9("html5_sabr_live_support_subfragmented_captions"))(n.U?n.U=g.Bc(n.U,M):(n.U=M,L4P(n.U)),n.U)?M.info.X&&(gC6(n.U),Ij6(n,n.U,m,h),n.U=null):g.op(n.logger,350058965,"Empty slice");
else if(M.info.X){var F=M;if(n.vL.length>0){for(F=n.vL.shift();n.vL.length>0;)F=g.Bc(F,n.vL.shift());F=g.Bc(F,M)}F?(L4P(F),gC6(F),Ij6(n,F,m,h)):g.op(n.logger,350058965,"Empty slice")}else n.vL.push(M)};
n.V.addEventListener("sabrCaptionsDataLoaded",n.j)},Ij6=function(n,m,M,h){var F=n.q9(m),e=F.x6;
F={formatId:F.formatId,startTimeMs:F.startTimeMs,durationMs:F.durationMs,FL:e,Gh:e};e=jAw(n.vA,F.startTimeMs);var P=e>=0?n.vA[e]:null,H=P?P.startTimeMs+P.durationMs:0,z=F.startTimeMs+F.durationMs;!P||F.startTimeMs-H>n.W?n.vA.splice(e+1,0,F):(P.durationMs=Math.max(H,z)-P.startTimeMs,P.Gh=Math.max(P.Gh,F.Gh));h(n.vA);h=g.bO(m);n=n.B;h=h.buffer.slice(h.byteOffset,h.byteLength+h.byteOffset);m=m.info.W;n.C?n.W==null?g.op(n.logger,350058965,"Null loaded track meta data at captions data received"):M.GB(h,
n.W,m*1E3):g.op(n.logger,350058965,"Null Representation at captions data received")},jAw=function(n,m){n=g.j5(n,{startTimeMs:m},function(M,h){return M.startTimeMs-h.startTimeMs});
return n>=0?n:-n-2},L4P=function(n){try{var m=g.ap(n)*1E3}catch(M){m=n.info.startTime*1E3}m<0&&(m=n.info.startTime*1E3);
n.info.startTime=m/1E3;n.info.W=m/1E3},gC6=function(n){try{var m=g.rb7(n)*1E3}catch(M){m=n.info.duration*1E3}m<0&&(m=n.info.duration*1E3);
n.info.duration=m/1E3;n.info.C=m/1E3},Hb=function(n,m){g.rX.call(this,m);
this.j=n;this.V=m;this.logger=new g.z_("caps");this.W=this.C=null;this.N=new XWV(this.V,this,this.logger,this.j.xq)},ROo=function(n,m){var M=[],h;
for(h in n.j.U)if(n.j.U.hasOwnProperty(h)){var F=n.j.U[h];if(g.Dh(F,m||null)){var e=F.info.id,P=e,H="."+e,z="",A="";if(F=F.info.captionTrack)e=F.languageCode,P=F.displayName,H=F.vssId,z=F.kind,A=F.id;M.push(new g.VF({id:h,languageCode:e,languageName:P,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:H,kind:z,captionId:A}))}}return M},W45=function(n,m,M){var h=[],F;
for(F in n.j.U)if(n.j.U.hasOwnProperty(F)){var e=n.j.U[F];if(g.Dh(e,M||null)){var P=e.info.captionTrack;P&&P.languageCode===m&&h.push(e)}}return h.length?h[0]:null},CvK=function(n,m){if(!g.VsB(n)||n.U!=null&&g.$BU(m,n.U)&&n.U.U.rawcc!=null)return!1;
m=!!n.U&&n.U.isManifestless&&Object.values(n.U.U).some(function(M){return g.Dh(M,"386")});
n=!!n.U&&!n.U.isManifestless&&g.GV7(n.U);return m||n},K46=function(){qi.call(this)},dQP=function(n){var m=ruH.length;
if(n.byteLength<m)return!1;n=new Uint8Array(n,0,m);for(var M=0;M<m;M++)if(ruH[M]!==n[M])return!1;return!0},DQS=function(n,m,M,h,F,e,P,H,z){switch(P.tagName){case "b":H.bold=!0;
break;case "i":H.italic=!0;break;case "u":H.underline=!0}for(var A=0;A<P.childNodes.length;A++){var b=P.childNodes[A];if(b.nodeType===3)b=new l_(m,M,h,F.id,b.nodeValue,e||A>0,g.ms(H)?void 0:H),z.push(b),F.U.push(b);else{var B={};Object.assign(B,H);DQS(n,m,M,h,F,!0,b,B,z)}}},SLV=function(n){var m=n.split(":");
n=0;m=g.Q(m);for(var M=m.next();!M.done;M=m.next())n=n*60+Number(M.value);return n*1E3},toP=function(n,m,M,h){h=Object.assign({XN:0},h);
return new Te(n,m,M,"_"+Ge++,h)},zm=function(n,m){g.p.call(this);
this.V=n;this.iq=m;this.U=null;this.zX=this.V.LK();this.logger=new g.z_("caps")},pWS=function(n,m,M){if(typeof m==="string"||Ndw(m))return[{trackData:m,
Rn:M}];if(typeof m==="string"&&m.substring(0,6)==="WEBVTT"||typeof m!=="string"&&dQP(m))return[{trackData:m,Rn:M}];var h=new DataView(m);if(h.byteLength<=8||h.getUint32(4)!==1718909296)return[];var F=g.dPL(h);if(n.zX&&F){var e=g.IB7(F),P=g.$PZ(F);F=F.segmentNumber;e&&F&&n.zX.lF(F,e,P)}n=g.Af(h,1835295092);if(!n||!n.length||!n[0].size)return[];e=[];for(P=0;P<n.length;P++)F=n[P],F=new Uint8Array(m,F.dataOffset,F.size-(F.dataOffset-F.offset)),F=g.vg(F),e.push({trackData:F,Rn:M+P*1E3});OeH(h,e,M);return e=
e.filter(function(H){return!!H.trackData})},OeH=function(n,m,M){var h=g.Mc(n,0,1836476516),F=9E4;
h&&(F=g.hf(h)||9E4);h=0;for(var e=g.Af(n,1836019558),P=0;P<e.length;P++){var H=e[P];P<m.length&&(H=g.Mc(n,H.dataOffset,1953653094))&&(H=g.Mc(n,H.dataOffset,1952867444))&&(H=g.zy(H)/F*1E3,P===0&&(h=H),m[P].Rn=H-h+M||M*P*1E3)}},fjY=function(n,m,M){n.U||(n.U=new K46);
n=n.U.X(m,M);Math.random()<.01&&g.F4(Error("Deprecated subtitles format in web player: WebVTT"));return n},vCw=function(n){var m={};
if(n=g.yF(n))m.lang=n,g.LIm.test(n)&&(m.qP=1);return m},TdV=function(n){g.CW.call(this,n);
var m=this;this.V=n;this.Iz=[];this.lq={};this.dW={};this.C=!1;this.X="NONE";this.U=this.k6=this.fP=this.vT=this.SU=null;this.Ua={Vn:function(){m.Vn()},
GB:function(e,P,H,z,A){A=A===void 0?0:A;var b,B=Number((b=m.videoData.S().Gv().U.oz(g.hy6))!=null?b:0);A>0&&B>0&&m.videoData.lengthSeconds>0&&A/m.videoData.lengthSeconds>B?m.V.uq("tts",{dropcap:A}):m.GB(e,P,H,z)}};
this.j=null;this.iq=this.V.S();this.videoData=this.V.getVideoData();this.kq=this.V.Z9();this.B={iI:{}};this.N={iI:{}};g.Rn(this.videoData)?this.X="OFFLINE":g.IHU(this.videoData,this.V)?this.X="HLS":CvK(this.videoData,this.V)?this.X="SABR_LIVE":g.jN_(this.videoData,this.V)?this.X="LIVE":this.videoData.captionTracks.length?this.X="INNERTUBE":this.videoData.CY&&(this.X="TTS");this.zv=this.iq.controlsType==="3";this.HT=new zm(this.V,this.iq);this.eU=new g.KH(this);this.G=new g.T({K:"div",L:"ytp-caption-window-container",
Y:{id:"ytp-caption-window-container"}});this.Uw={top:0,right:0,bottom:0,left:0,width:1,height:1};var M=null,h=g.xN("yt-html5-player-modules::subtitlesModuleData");h&&(M=new g.EM(h));this.storage=M;var F;this.rL=!((F=n.S$())==null||!F.iF());this.W=ljY(this);this.BT=!this.W&&this.zv&&this.rL&&(this.X==="LIVE"||this.X==="SABR_LIVE");g.f(this,this.HT);this.W?this.Ow=this.Vi=null:(this.Vi=new g.jp(this.hm,void 0,this),g.f(this,this.Vi),this.Ow=new g.Rd(this.Jo9,2E3,this),g.f(this,this.Ow));g.f(this,this.eU);
g.UV(this.player,this.G.element,4);g.f(this,this.G);this.W||this.eU.D(n,"resize",this.UI);(this.Xq=g.RL(this.iq)&&!g.AR()&&!this.V.isFullscreen()&&!this.W&&!this.BT)&&this.eU.D(n,"resize",this.bFi);this.eU.D(n,"onPlaybackAudioChange",this.RpU);this.eU.D(n,g.zV("captions"),function(e){m.onCueRangeEnter(e)});
this.eU.D(n,g.oP("captions"),function(e){m.onCueRangeExit(e)});
qL_(this,Idq()||{});this.player.mP("onCaptionsModuleAvailable");this.X==="HLS"&&this.W&&(n=this.V.S$().Bd(),this.rL&&this.eU.D(n.textTracks,"addtrack",this.vC7))},JuK=function(n){if(n.iq.YM===1||n.videoData.xz===1||g.eO(n.videoData,"yt:cc")==="alwayson")return!0;
if(n.videoData.captionTracks.length)var m=n.getAudioTrack().j;if(n.iq.J("enable_player_captions_persistence_state_machine")){var M=n.iq.J("enable_player_captions_persistence_state_machine")?g.Ij("yt-player-caption-persistence"):void 0;if(M!==void 0)return!!M}else if(n.iq.YM===2){if(g.el(n.iq))M=GhH(n);else if(n.storage)try{M=n.storage.get("module-enabled")}catch(F){n.storage.remove("module-enabled")}else M=null;if(M!=null)return!!M}M=y97(n.player.getAudioTrack(),g.el(n.iq));var h=g.eO(n.videoData,
"yt:cc");if(khw(n)===void 0){if(M==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return h?h==="on":!0;if(M==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return h==="on"}else return h==="on";return m==="ON"||g.eO(n.videoData,"yt:cc")==="on"},oD=function(n,m){if(n.j&&(m===void 0||!m)||!n.videoData.captionTracks.length)return!1;
n=n.getAudioTrack();return!!n.U||n.j==="FORCED_ON"},khw=function(n){if(!n.iq.J("enable_player_captions_persistence_state_machine")){var m=void 0,M=g.hh().oz(65);
if(g.el(n.iq)&&M!=null){if(GhH(n)!=null)return!1;m=!M}return m}},bY=function(n,m){if(!n.U)return null;
if(n.k6&&n.k6.W)return n.k6.W;m=UQH(n,m);m=g.AS(n.U.U,m);var M=null;if(NOq(n.iq)){var h=n.V.isInline()?void 0:g.Ij("yt-player-caption-sticky-language");for(var F=[h,n.videoData.captionsLanguagePreference,n.iq.captionsLanguagePreference,g.eO(n.videoData,"yt:cc_default_lang")],e=!1,P=0;P<F.length;P++){var H=F[P];if(H){e=!0;for(var z=0;z<m.length;z++)if(g.yF(m[z])===H)return m[z];for(z=0;z<m.length;z++)if(g.yF(m[z]).split("-")[0]===H.split("-")[0])return m[z]}}if(e&&n.U&&(F=n.U.B,F.length))for(F=g.Q(F),
e=F.next();!e.done;e=F.next())if(e=e.value,e.languageCode===h){M=e;break}}else for(h=[n.videoData.captionsLanguagePreference,n.iq.captionsLanguagePreference,g.eO(n.videoData,"yt:cc_default_lang")],F=0;F<h.length;F++)for(e=0;e<m.length;e++)if(g.yF(m[e])===h[F])return m[e];h=null;n.k6&&n.k6.X&&(h=n.k6.X);h||(h=m.find(function(A){return A.isDefault})||null);
h||(h=m[0]||AA(n));h&&M&&g.yF(h).split("-")[0]!==M.languageCode.split("-")[0]&&(h=wUS(h,M));return h},AA=function(n){return n.k6&&n.k6.U},Bb=function(n){var m=AA(n);
return!!m&&n.j===m},cuK=function(n,m){if(n.j){var M=n.V.S$().Bd().textTracks,h=null;
n.X==="HLS"?h=n.j.getId():h=n.j.toString();for(var F=0;F<M.length;F++){var e=M[F];e.id===h&&(m?e.mode!=="showing"&&(e.mode="showing",e=n.j,n.Vg(e,!!e,Bb(n)?"g":n.C?"m":"s")):e.mode==="showing"&&(e.mode="disabled"))}}},wp=function(n,m,M){n.loaded&&n.unload();
M!=null&&(n.C=M,n.C&&(n.iq.J("enable_player_captions_persistence_state_machine")?aD(n,!!m):g.el(n.iq)?V3(n,!!m):xu(n,!!m)));m!==null||oD(n,!0)||n.Vg(m,!!m,n.C?"m":"s");n.j=m;oD(n)&&(n.j=AA(n));var h;sAo(n,(h=n.j)!=null?h:void 0);n.load()},n6Y=function(n,m){if(m instanceof Te){var M=n.lq[m.id];
M&&M.j!==m&&(M.dispose(),delete n.lq[m.id],M=null);M||(M=uxm(n,m))&&(n.lq[m.id]=M)}else M=m.windowId,n.dW[M]||(n.dW[M]=[]),n.dW[M].push(m)},uxm=function(n,m){var M=m87(n);
if(!M)return null;var h=n.j?g.yF(n.j):null;h&&g.LIm.test(h)&&(m.params.qP=1);var F=n.kq.getPlayerSize();h=F.height*n.Uw.height;F=F.width*n.Uw.width;n.iq.playerStyle!=="google-live"||n.B.isDefault||Object.assign(m.params,n.B);switch(m.params.XN!=null?m.params.XN:m.U.length>1?1:0){case 1:return new hA(m,n.B,n.N,M.width,M.height,F,h,n.iq.experiments,n.LG.bind(n),n.V);case 2:return new ET(m,n.B,n.N,M.width,M.height,F,h,n.iq.experiments,n.LG.bind(n),n.V);default:return new rN(m,n.B,n.N,M.width,M.height,
F,h,n.iq.experiments,n.LG.bind(n),n.V)}},qL_=function(n,m,M){M=M===void 0?!1:M;
var h=y3.iI;n.B={};Object.assign(n.B,y3);n.B.iI={};Object.assign(n.B.iI,h);n.N={iI:{}};var F=m.backgroundOverride?n.N:n.B,e=m.background||h.background;s6.test(e);F.iI.background=e;F=m.colorOverride?n.N:n.B;e=m.color||h.color;s6.test(e);F.iI.color=e;F=m.windowColorOverride?n.N:n.B;e=m.windowColor||y3.windowColor;s6.test(e);F.windowColor=e;F=m.backgroundOpacityOverride?n.N:n.B;e=m.backgroundOpacity;e==null&&(e=h.backgroundOpacity);F.iI.backgroundOpacity=e;F=m.fontSizeIncrementOverride?n.N:n.B;e=m.fontSizeIncrement;
e==null&&(e=h.fontSizeIncrement);F.iI.fontSizeIncrement=e;e=m.fontStyleOverride?n.N:n.B;F=m.fontStyle;F==null&&(F=h.bold&&h.italic?3:h.bold?1:h.italic?2:0);e=e.iI;switch(F){case 1:e.bold=!0;delete e.italic;break;case 2:delete e.bold;e.italic=!0;break;case 3:e.bold=!0;e.italic=!0;break;default:delete e.bold,delete e.italic}F=m.textOpacityOverride?n.N:n.B;e=m.textOpacity;e==null&&(e=h.textOpacity);F.iI.textOpacity=e;F=m.windowOpacityOverride?n.N:n.B;e=m.windowOpacity;e==null&&(e=y3.windowOpacity);F.windowOpacity=
e;F=m.charEdgeStyleOverride?n.N:n.B;e=m.charEdgeStyle;e==null&&(e=h.charEdgeStyle);F.iI.charEdgeStyle=e;F=m.fontFamilyOverride?n.N:n.B;e=m.fontFamily;e==null&&(e=h.fontFamily);F.iI.fontFamily=e;n.loaded&&n.UI();M&&g.gu("yt-player-caption-display-settings",m,2592E3)},MUH=function(n,m){if(!n.U)return{};
if(m){g.ms(m)||n.GI(m.vss_id,"m");if(n.W&&n.X!=="HLS"||!g.sN(m))return;if(g.ms(m)){wp(n,null,!0);return}for(var M,h=g.AS(n.U.U,!0),F=0;F<h.length;F++){var e=h[F];e.languageCode!==m.languageCode||M&&(e.languageName!==m.languageName||(e.captionId||"")!==(m.captionId||"")||g.xj(e)!==m.displayName)||(M=m.translationLanguage?wUS(e,m.translationLanguage):e)}n.au(m.position);!M||M===n.j&&n.loaded||(m=g.P1(),h=g.yF(M),m.length&&h===m[m.length-1]||(m.push(h),g.gu("yt-player-caption-language-preferences",m)),
NOq(n.iq)&&!n.V.isInline()&&g.gu("yt-player-caption-sticky-language",h,2592E3),wp(n,M,!0))}else return n.loaded&&n.j&&!Bb(n)?g.wj(n.j):{};return""},FtY=function(n,m,M){m&&!n.fP?(m=Bd7({qP:0,
lang:"pl"}),n.fP=[m,new l_(m.start,m.end-m.start,0,m.id,M!=null?M:"Napisy b\u0119d\u0105 wygl\u0105da\u0142y tak")],n.player.Zx(n.fP)):!m&&n.fP&&(h8S(n,n.fP),n.fP=null)},h8S=function(n,m){n.player.a5(m);
m=g.Q(m);for(var M=m.next();!M.done;M=m.next())g.xq(n.Iz,M.value);WT(n.Vi)},sAo=function(n,m){n.iq.J("html5_modify_caption_vss_logging")&&(n.videoData.KO=m)},m87=function(n){var m=n.kq.getVideoContentRect(!0).height,M=n.kq.getVideoContentRect(!0).width;
if(!m||!M)return null;m*=n.Uw.height;M*=n.Uw.width;return{width:M,height:m}},xu=function(n,m){if(n.storage)try{n.storage.set("module-enabled",m)}catch(M){}},V3=function(n,m){n.V.isInline()||g.gu("yt-player-sticky-caption",m,2592E3)},GhH=function(n){if(!n.V.isInline())return g.Ij("yt-player-sticky-caption")},aD=function(n,m){n.iq.J("enable_player_captions_persistence_state_machine")&&g.gu("yt-player-caption-persistence",m,3122064E3)},ljY=function(n){var m,M=!((m=n.V.S$())==null||!m.Z3());
return n.X==="HLS"&&M?!0:n.zv&&M&&n.X!=="LIVE"&&n.X!=="SABR_LIVE"},UQH=function(n,m){if(n.X==="HLS")return!1;
g.wf(n.videoData)&&(m=!0);m||(m=n.X==="TTS"?!1:n.X==="INNERTUBE"?!1:!0);return m||n.iq.J("web_watch_disable_account_level_captions_settings")&&g.el(n.iq)?!0:!!g.hh().oz(66)};
g.bm.prototype.lF=g.e3(64,function(n,m,M){this.j.set(n,{bx:m,vX:M})});
g.Br.prototype.lF=g.e3(63,function(n,m,M){this.fP.lF(n,m,M)});
g.rX.prototype.E7=g.e3(62,function(){return!1});
g.rX.prototype.u8=g.e3(61,function(){});
g.dX.prototype.u8=g.e3(60,function(n,m,M){var h=this;this.F6();m=this.Zf(n,m);var F=this.NG.S().J("html5_report_captions_ctmp_qoe"),e=(0,g.Vn)();this.WF();xhH(this,m,{format:"RAW",onSuccess:function(P){h.j=null;if(F){var H=(P.responseText.length/1024).toFixed(),z=(0,g.Vn)();h.videoData.uq("capresp",{ms:z-e,kb:H})}H=P.getResponseHeader&&P.getResponseHeader("Content-Length")?Number(P.getResponseHeader("Content-Length")):0;M.GB(P.responseText,n,void 0,void 0,H)},
onError:F?function(P){var H;P=(H=P==null?void 0:P.status)!=null?H:0;h.videoData.uq("capfail",{status:P})}:void 0,
withCredentials:!0})});
g.S9.prototype.u8=g.e3(59,function(n,m,M){var h=this;this.F6();m=this.Zf(n,m);this.WF();this.j=g.aX(m,{format:"RAW",onSuccess:function(F){h.j=null;var e=F.getResponseHeader&&F.getResponseHeader("Content-Length")?Number(F.getResponseHeader("Content-Length")):0;M.GB(F.responseText,n,void 0,void 0,e)},
withCredentials:!0})});
g.MM.prototype.QV=g.e3(58,function(){for(var n=g.UO(document,"track",void 0,this.U),m=0;m<n.length;m++)g.EZ(n[m])});
g.cv.prototype.QV=g.e3(57,function(){this.mediaElement.QV()});
g.MM.prototype.iF=g.e3(56,function(){return!(!this.U.textTracks||!this.U.textTracks.addEventListener)});
g.cv.prototype.iF=g.e3(55,function(){return this.mediaElement.iF()});
g.MM.prototype.Z3=g.e3(54,function(){return!!this.U.textTracks});
g.cv.prototype.Z3=g.e3(53,function(){return this.mediaElement.Z3()});
g.MM.prototype.w8=g.e3(52,function(n){for(var m=0;m<n.length;m++)this.U.appendChild(n[m])});
g.cv.prototype.w8=g.e3(51,function(n){this.mediaElement.w8(n)});
g.vM.prototype.U3=g.e3(39,function(n){return this.app.b0({playerType:void 0}).U3(n)});
g.nO.prototype.U3=g.e3(38,function(n){return this.rW.Pn.U3(n)});
g.OF.prototype.U3=g.e3(37,function(n){return this.N8().some(function(m){return m.namespace===n})});
g.Mf.prototype.U3=g.e3(36,function(){return!1});
g.vM.prototype.GI=g.e3(34,function(n,m){this.app.gW().GI(n,m)});
g.nO.prototype.GI=g.e3(33,function(n,m){this.rW.GI(n,m)});
g.nr.prototype.GI=g.e3(32,function(n,m){n=[n,m];g.uF(this,g.M_(this.provider),"cfi",n)});
g.SJ.prototype.GI=g.e3(31,function(n,m){this.qoe&&this.qoe.GI(n,m)});
g.z7.prototype.GI=g.e3(30,function(n,m){this.DA.GI(n,m)});
g.Mf.prototype.GI=g.e3(29,function(){});
g.vM.prototype.Vg=g.e3(28,function(n,m,M){this.app.gW().Vg(n,m,M)});
g.nO.prototype.Vg=g.e3(27,function(n,m,M){this.rW.Vg(n,m,M)});
g.nr.prototype.Vg=g.e3(26,function(n,m,M){if(this.Ow!==n||this.Yq!==m)m=m==="rawcc"?"":m,M=[n,m,this.Ow,M],g.uF(this,g.M_(this.provider),"cfs",M),this.Ow=n,this.Yq=m});
g.SJ.prototype.Vg=g.e3(25,function(n,m,M){this.qoe&&this.qoe.Vg(n,m,M)});
g.z7.prototype.Vg=g.e3(24,function(n,m,M){this.DA.Vg(n,m,M)});
g.Mf.prototype.Vg=g.e3(23,function(){});
g.fl.prototype.e_=g.e3(3,function(n){return(n=this.tY(n))?n.U:0});
g.yE.prototype.e_=g.e3(2,function(){return 0});
var XUw=/#(.)(.)(.)/,ZBV=/^#(?:[0-9a-f]{3}){1,2}$/i,K35={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Arab:"Kazakh (Arabic)",kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",ku_Latn:"Kurdish (Latin)",kum:"Kumyk",kut:"Kutenai",kv:"Komi",
kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",
maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",
mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",
nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pms:"Piedmontese",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",
pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",
sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",
sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelauan",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",
tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",
vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",
zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"},iLK={en:"English"};g.y($hY,g.rX);
$hY.prototype.UN=function(n){var m=this.NG.S$();if(m&&m.Bd()){m=m.Bd().textTracks;m=g.Q(m);for(var M=m.next();!M.done;M=m.next())M=M.value,M.kind==="subtitles"&&!this.j.has(M.language)&&M.language&&(g.KW(this.U,new g.VF({languageCode:M.language,languageName:M.language,kind:M.kind,id:M.id,displayName:iLK[M.label]||M.label,vss_id:"."+M.language})),this.j.add(M.language))}g.AS(this.U).length>0&&n.Vn()};
CZ.prototype.contains=function(n){n=g.j5(this.segments,n);return n>=0||n<0&&(-n-1)%2===1};
CZ.prototype.length=function(){return this.segments.length/2};
g.y(RZY,g.p);g.w=RZY.prototype;g.w.jU=function(){g.p.prototype.jU.call(this);this.j&&this.j.cancel()};
g.w.Kt=function(){this.seekTo(this.player.getCurrentTime())};
g.w.seekTo=function(n){n-=this.player.gL();var m=this.U;this.U=g.HP(this.X6.Yl(n).pP);m!==this.U&&this.k6&&this.k6()};
g.w.reset=function(){this.W=new CZ;this.N=-1;this.j&&(this.j.cancel(),this.j=null)};
g.w.dV=function(){this.F6();var n;if(n=this.U!=null)n=this.U,n=n.X6.u7(n);if(n&&!this.j&&!(this.U&&this.U.startTime-this.player.getCurrentTime()>30)){n=this.U;n=n.X6.a6(n);var m=n.pP[0],M;if((M=this.player.getVideoData())==null?0:M.enableServerStitchedDai)if(M=this.player.LK()){var h=m.X6.info.id,F=m.x6,e=n.pP[0].W;if(this.policy.Ow){if(M=g.Il_(M,e,F,h,3))n.W=M}else if(h=M.S7(e,F,h,3))if(e=2,M.Wg.has(F)?e=0:g.Ov_(M,F)&&(e=1),M=e,M===0)h&&(n.U=new g.Uw(h));else if(M===2){this.C.start();W3P(this)&&
this.seekTo(this.player.getCurrentTime());return}}m.X6.index.Nn(m.x6)?(this.W.contains(n.pP[0].x6)||C8H(this,n),this.U=g.HP(n.pP)):W3P(this)&&this.seekTo(this.player.getCurrentTime())}this.C.start()};
g.y(KZ,g.rX);g.w=KZ.prototype;g.w.u8=function(n,m,M){var h=this;this.WF();m=dhP(this,n.getId());m||(m=n.languageCode,m=this.j.isManifestless?DhK(this,m,"386"):DhK(this,m));if(m){var F=(m.index.e_(m.index.Iq())-m.index.getStartTime(m.index.Iq()))*1E3,e=new g.N9B(this.V.S());this.W=new RZY(e,this.V,m,function(P,H){M.GB(P,n,H,F)},this.C||g.eN(m.info),function(){h.W&&h.W.reset();
h.N=!0})}};
g.w.E7=function(){var n=this.N;this.N=!1;return n};
g.w.UN=function(n){var m=this.V.S().J("html5_fallback_if_rawcc_missing");var M=this.j.U.rawcc!=null;if(!this.C||!M&&m)m=this.j.isManifestless?r9w(this,"386"):r9w(this);else{if(!M){g.op(this.logger,386248249,"rawcc used but unavailable");return}m=[new g.VF({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.VF({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}m=g.Q(m);
for(M=m.next();!M.done;M=m.next())g.KW(this.U,M.value);n.Vn()};
g.w.WF=function(){this.W&&(this.W.dispose(),this.W=null)};
g.w.Zf=function(){return""};
var s6=/^#(?:[0-9a-f]{3}){1,2}$/i;var OBS=["left","right","center","justify"];g.y(rN,g.T);g.w=rN.prototype;g.w.s8=function(n,m){this.SU=n;this.rL=m;var M=g.pV(this.element,this.element.parentElement);this.kq=n-M.x;this.Ua=m-M.y};
g.w.gH=function(n,m){if(n!==this.SU||m!==this.rL){g.On(this.element,"ytp-dragging")||g.pR(this.element,"ytp-dragging");var M=g.v3(this.element);n=n-this.kq-.02*this.VC;var h=m-this.Ua-.02*this.e$,F=(n+M.width/2)/this.maxWidth*3;F=Math.floor(g.W6(F,0,2));var e=(h+M.height/2)/this.maxHeight*3;e=Math.floor(g.W6(e,0,2));m=F+e*3;n=(n+F/2*M.width)/this.maxWidth;n=g.W6(n,0,1)*100;M=(h+e/2*M.height)/this.maxHeight;M=g.W6(M,0,1)*100;this.j.params.kM=m;this.j.params.Eb=M;this.j.params.zt=n;this.j.params.isDefault=
!1;this.U.kM=m;this.U.Eb=M;this.U.zt=n;this.U.isDefault=!1;this.lq.kM=m;this.lq.Eb=M;this.lq.zt=n;this.lq.isDefault=!1;this.Uq()}};
g.w.RN=function(){g.v9(this.element,"ytp-dragging")};
g.w.Uq=function(){this.je(this.N)};
g.w.je=function(n){var m=this.Xq?0:Math.min(this.Gu(),this.maxWidth),M=this.Sn(),h=this.Xq;if(h){var F=getComputedStyle(this.X.parentNode);F=dN(F.borderLeftWidth)+dN(F.borderRightWidth)+dN(F.paddingLeft)+dN(F.paddingRight)}else F=0;var e=F;F="";this.j.params.qP===3&&(F="rotate(180deg)");var P=h?"calc(96% - "+e+"px)":"96%";g.W3(this.element,{top:0,left:0,right:"",bottom:"",width:m?m+"px":"",height:M?M+"px":"","max-width":P,"max-height":P,margin:"",transform:""});this.Rm(n);F={transform:F,top:"",left:"",
width:m?m+"px":"",height:M?M+"px":"","max-width":"","max-height":""};P=this.U.kM;var H=this.U.zt,z=this.U.Eb;this.HT&&P!=null&&(H=50,P=Math.floor(P/3)*3+1);H=H*.96+2;switch(P){case 0:case 3:case 6:(h=this.U.iI.fontSizeIncrement)&&h>0&&this.U.qP!==2&&this.U.qP!==3&&(H=Math.max(H/(1+h*2),2));F.left=H+"%";break;case 1:case 4:case 7:F.left=H+"%";H=0;this.G||(H=this.X.offsetWidth);m||H?(m=m||H+1,F.width=m+"px",F["margin-left"]=h?m/-2-e/2+"px":m/-2+"px"):(this.G&&(F.width="max-content"),F.transform+=" translateX(-50%)");
break;case 2:case 5:case 8:F.right=100-H+"%"}h=z*.96+2;switch(P){case 0:case 1:case 2:F.top=h+"%";break;case 3:case 4:case 5:F.top=h+"%";h=0;this.G||(h=this.element.clientHeight);(M=M||h)?(F.height=M+"px",F["margin-top"]=M/-2+"px"):F.transform+=" translateY(-50%)";break;case 6:case 7:case 8:F.bottom=100-h+"%"}g.W3(this.element,F);if(this.B){if(this.G)M=this.dW;else{if(this.HT&&n.length===0)n=0;else{M=1;for(h=0;h<n.length;h++)F=n[h],typeof F.text==="string"&&(M+=F.text.split("\n").length-1,F.append||
h===0||M++);n=M}M=this.HT?n>0?this.X.offsetHeight/n:0:this.X.offsetHeight/n}this.B.style.height=M+"px";this.B.style.width=M+"px";this.element.style.paddingLeft=M+5+"px";this.element.style.paddingRight=M+5+"px";this.G||(n=Number(this.element.style.marginLeft.replace("px",""))-M-5,M=Number(this.element.style.marginRight.replace("px",""))-M-5,this.element.style.marginLeft=n+"px",this.element.style.marginRight=M+"px")}};
g.w.Rm=function(n){var m;for(m=0;m<n.length&&n[m]===this.N[m];m++);if(this.Iz||this.N.length>m)m=0,this.Iz=!1,this.N=[],this.C=this.Ow=this.Vi=null,g.eL(this.X);for(;m<n.length;m++)q5o(this,n[m])};
g.w.Gu=function(){return 0};
g.w.Sn=function(){return 0};
g.w.toString=function(){return g.T.prototype.toString.call(this)};GRm.prototype.clear=function(){this.X=this.time=this.mode=0;this.U=[];this.reset()};
GRm.prototype.reset=function(){this.mode=0;this.W.reset(0);this.B.reset(1)};
var kRw=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Dx.prototype.set=function(n){this.type=n};
Dx.prototype.get=function(){return this.type};
SE.prototype.clear=function(){this.state=0};
SE.prototype.update=function(){this.state=this.state===2?1:0};
SE.prototype.Jj=function(){return this.state!==0};
SE.prototype.matches=function(n,m){return this.Jj()&&n===this.mf&&m===this.KX};
uB6.prototype.reset=function(){this.timestamp=this.U=0};
tv.prototype.updateTime=function(n){for(var m=1;m<=15;++m)for(var M=1;M<=32;++M)this.X[m][M].timestamp=n};
tv.prototype.debugString=function(){for(var n="\n",m=1;m<=15;++m){for(var M=1;M<=32;++M){var h=this.X[m][M];n=h.U===0?n+"_":n+String.fromCharCode(h.U)}n+="\n"}return n};
tv.prototype.reset=function(n){for(var m=0;m<=15;m++)for(var M=0;M<=32;M++)this.X[m][M].reset();this.W=n;this.U=0;this.j=this.row=1};
var nC_=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],mQw=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],MoS=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],hO7=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];PvS.prototype.reset=function(n,m){this.B=m;this.style.set(2);this.j=this.N;this.W=this.C;this.U=this.j;var M=(n<<2)+(m<<1);this.N.reset(M);this.C.reset(M);this.text.reset((n<<2)+(m<<1)+1)};
TO_.prototype.reset=function(n){this.B=n;this.j.clear();this.W=this.X;this.X.reset(n,0);this.N.reset(n,1)};oCq.prototype.W=function(){};g.y(l_,g.E4);l_.prototype.toString=function(){return g.E4.prototype.toString.call(this)};g.y(qi,g.p);qi.prototype.reset=function(){};g.y(Te,g.E4);Te.prototype.toString=function(){return g.E4.prototype.toString.call(this)};
var Ge=0;g.y(ko,qi);ko.prototype.reset=function(){this.C={};this.j=this.U=null;this.N=!0};
ko.prototype.X=function(n,m){n=n.firstChild;n.getAttribute("format");m=m||0;Number.isFinite(m);n=Array.from(n.childNodes);n=g.Q(n);for(var M=n.next();!M.done;M=n.next())if(M=M.value,M.nodeType===1)switch(M.tagName){case "head":var h=M;break;case "body":var F=M}if(h)for(h=Array.from(h.childNodes),h=g.Q(h),n=h.next();!n.done;n=h.next())if(n=n.value,n.nodeType===1)switch(n.tagName){case "pen":M=n.getAttribute("id");var e=this.pens,P={},H=n.getAttribute("p");H&&Object.assign(P,this.pens[H]);H=U6(n,"b");
H!=null&&(P.bold=H);H=U6(n,"i");H!=null&&(P.italic=H);H=U6(n,"u");H!=null&&(P.underline=H);H=cT(n,"et");H!=null&&(P.charEdgeStyle=H);H=cT(n,"of");H!=null&&(P.offset=H);H=u_(n,"bc");H!=null&&(P.background=H);H=u_(n,"ec");H!=null&&(P.XW=H);H=u_(n,"fc");H!=null&&(P.color=H);H=cT(n,"fs");H!=null&&H!==0&&(P.fontFamily=H);H=Jv(n,"sz");H!==void 0&&(P.fontSizeIncrement=H/100-1);H=Jv(n,"bo");H!==void 0&&(P.backgroundOpacity=H/255);H=Jv(n,"fo");H!==void 0&&(P.textOpacity=H/255);H=cT(n,"rb");H!=null&&H!==10&&
H!==0&&(P.jc=H>10?H-1:H);n=cT(n,"hg");n!=null&&(P.yz=n);e[M]=P;break;case "ws":M=n.getAttribute("id");this.k6[M]=ajS(this,n);break;case "wp":M=n.getAttribute("id"),this.G[M]=Vow(this,n)}if(F){h=[];F=Array.from(F.childNodes);F=g.Q(F);for(n=F.next();!n.done;n=F.next())if(n=n.value,n.nodeType===1)switch(n.tagName){case "w":this.U=xQ_(this,n,m,!1);(n=this.C[this.U.id])&&n.end>this.U.start&&(n.end=this.U.start);this.C[this.U.id]=this.U;h.push(this.U);break;case "p":var z=n;H=m;M=[];e=z.getAttribute("w")||
this.B;P=!!U6(z,"a");H=(Jv(z,"t")||0)+H;var A=Jv(z,"d")||5E3;P||(!this.N&&this.j&&this.j.windowId===e&&this.j.end>H&&(this.j.end=H),this.j&&this.j.text==="\n"&&(this.j.text=""));var b=P?6:5,B=z.getAttribute("p");B=B?this.pens[B]:null;var V=Array.from(z.childNodes);V.length&&(this.N=z.getAttribute("d")!=null);for(z=0;z<V.length;z++){var a=V[z],x=void 0;z>0&&(P=!0);var Y=void 0;a.nodeType===1&&(Y=a);if(Y&&Y.tagName==="s"){if((a=(a=Y.getAttribute("p"))?this.pens[a]:null)&&a.jc&&(a.jc===1?(a=V.slice(z,
z+4),a.length===4&&(x=beS(H,A,e,P,b,a,this.pens),z+=3)):x=beS(H,A,e,P,b,[Y],this.pens)),!x){var X=Y;x=H;Y=A;a=e;var N=P,C=b,K=X.textContent?X.textContent:"",d=X.getAttribute("p");d=d?this.pens[d]:null;X=Jv(X,"t")||0;x=new l_(x+X,Y-X,C,a,K,N,d)}}else x=new l_(H,A,b,e,a.textContent||"",P,B);M.push(x);this.j=x}if(M.length>0)for(M[0].windowId===this.B&&(this.U=xQ_(this,n,m,!0),h.push(this.U)),n=g.Q(M),M=n.next();!M.done;M=n.next())M=M.value,M.windowId=this.U.id,this.U.U.push(M),h.push(M)}m=h}else m=[];
return m};var e8_=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.y(nI,qi);nI.prototype.reset=function(){this.j.clear()};
nI.prototype.X=function(n,m){var M=JSON.parse(n);if(!M)return[];if(M.pens){n=0;for(var h=g.Q(M.pens),F=h.next();!F.done;F=h.next()){F=F.value;var e={},P=F.pParentId;P&&Object.assign(e,this.U.get(P));F.bAttr&&(e.bold=!0);F.iAttr&&(e.italic=!0);F.uAttr&&(e.underline=!0);P=F.ofOffset;P!=null&&(e.offset=P);F.szPenSize!==void 0&&(e.fontSizeIncrement=F.szPenSize/100-1);P=F.etEdgeType;P!=null&&(e.charEdgeStyle=P);F.ecEdgeColor!==void 0&&(e.XW=m9(F.ecEdgeColor));P=F.fsFontStyle;P!=null&&P!==0&&(e.fontFamily=
P);F.fcForeColor!==void 0&&(e.color=m9(F.fcForeColor));F.foForeAlpha!==void 0&&(e.textOpacity=F.foForeAlpha/255);F.bcBackColor!==void 0&&(e.background=m9(F.bcBackColor));F.boBackAlpha!==void 0&&(e.backgroundOpacity=F.boBackAlpha/255);(P=F.rbRuby)&&P!==10&&(e.jc=P>10?P-1:P,e.textEmphasis=e8_.get(e.jc));F.hgHorizGroup&&(e.yz=F.hgHorizGroup);this.U.set(n++,e)}}if(M.wsWinStyles)for(n=0,h=g.Q(M.wsWinStyles),F=h.next();!F.done;F=h.next())F=F.value,e={},(P=F.wsParentId)?Object.assign(e,this.B.get(P)):Object.assign(e,
this.N),F.mhModeHint!==void 0&&(e.XN=F.mhModeHint),F.juJustifCode!==void 0&&(e.textAlign=F.juJustifCode),F.pdPrintDir!==void 0&&(e.qP=F.pdPrintDir),F.sdScrollDir!==void 0&&(e.RT=F.sdScrollDir),F.wfcWinFillColor!==void 0&&(e.windowColor=m9(F.wfcWinFillColor)),F.wfoWinFillAlpha!==void 0&&(e.windowOpacity=F.wfoWinFillAlpha/255),this.B.set(n++,e);if(M.wpWinPositions)for(n=0,h=g.Q(M.wpWinPositions),F=h.next();!F.done;F=h.next())F=F.value,e={},(P=F.wpParentId)&&Object.assign(e,this.W.get(P)),F.ahHorPos!==
void 0&&(e.zt=F.ahHorPos),F.apPoint!==void 0&&(e.kM=F.apPoint),F.avVerPos!==void 0&&(e.Eb=F.avVerPos),F.ccCols!==void 0&&(e.Fx=F.ccCols),F.rcRows!==void 0&&(e.b8=F.rcRows),this.W.set(n++,e);if(M.events){n=[];M=g.Q(M.events);for(h=M.next();!h.done;h=M.next()){var H=h.value;F=(H.tStartMs||0)+m;e=H.dDurationMs||0;if(H.id)P=String(H.id),h=wWV(this,H,F,e,P),n.push(h),this.j.set(P,h);else{H.wWinId?P=H.wWinId.toString():(P="_"+Ge++,h=wWV(this,H,F,e,P),n.push(h),this.j.set(P,h));h=n;var z=H;e===0&&(e=5E3);
H=this.j.get(P);var A=!!z.aAppend,b=A?6:5,B=z.segs,V=null;z.pPenId&&(V=this.U.get(z.pPenId));for(z=0;z<B.length;z++){var a=B[z],x=a.utf8;if(x){var Y=a.tOffsetMs||0,X=null;a.pPenId&&(X=this.U.get(a.pPenId));if((H.params.XN!=null?H.params.XN:H.U.length>1?1:0)===2&&A&&x==="\n")continue;a=null;var N=[],C;if(C=X&&X.jc===1){C=B;var K=z;if(K+3>=C.length||!C[K+1].pPenId||!C[K+2].pPenId||!C[K+3].pPenId)C=!1;else{var d=C[K+1].pPenId;(d=this.U.get(d))&&d.jc&&d.jc===2?(d=C[K+2].pPenId,d=this.U.get(d),!d||!d.jc||
d.jc<3?C=!1:(d=C[K+3].pPenId,C=(d=this.U.get(d))&&d.jc&&d.jc===2?!0:!1)):C=!1}}if(C)Y=B[z+1].utf8,a=B[z+3].utf8,C=B[z+2].utf8,K=this.U.get(B[z+2].pPenId),x=Auw(x,Y,C,a,K),a=new l_(F,e,b,P,x,A,X),z+=3;else{if(x.indexOf("<")>-1){var t=void 0;N=X;C=V;K=F;d=e;var l=Y,U=b,nN=A,FI=[],mX=g.zd("<html>"+x+"</html>");if(!mX.getElementsByTagName("parsererror").length&&((t=mX.firstChild)==null?0:t.childNodes.length))for(t=g.Q(mX.firstChild.childNodes),mX=t.next();!mX.done;mX=t.next()){mX=mX.value;var AU=void 0,
u=void 0,N7=(u=(AU=mX.textContent)==null?void 0:AU.replace(/\n/g,""))!=null?u:"";if(mX.nodeType!==3||N7&&N7.match(/^ *$/)==null){AU={};Object.assign(AU,N||C);u=void 0;switch((u=mX)==null?void 0:u.tagName){case "b":AU.bold=!0;break;case "i":AU.italic=!0;break;case "u":AU.underline=!0}FI.push(new l_(K+l,d-l,U,H.id,N7,nN,AU))}}N=FI}N.length||(N=[new l_(F+Y,e-Y,b,H.id,x,A,X||V)])}if(N.length)for(A=g.Q(N),X=A.next();!X.done;X=A.next())X=X.value,h.push(X),H.U.push(X);else a&&(h.push(a),H.U.push(a))}A=!0}}}m=
n}else m=[];return m};g.y(Ms,g.rX);Ms.prototype.u8=function(n,m,M){Q26(this.videoData.videoId,n.vssId,M.GB)};
Ms.prototype.UN=function(n){if(this.audioTrack)for(var m=g.Q(this.audioTrack.captionTracks),M=m.next();!M.done;M=m.next())g.KW(this.U,M.value);n.Vn()};g.y(hA,rN);hA.prototype.Rm=function(n){var m=this.j.U;rN.prototype.Rm.call(this,n);for(n=n.length;n<m.length;n++){var M=m[n];if(e&&M.U===F)var h=e;else{h={};Object.assign(h,M.U);Object.assign(h,P1K);var F=M.U;var e=h}q5o(this,M,h)}};
var P1K={jps:!0};g.y(Fq,oCq);Fq.prototype.W=function(n,m,M,h,F){if(M<h){var e="_"+Ge++;M=M/1E3-this.N;h=h/1E3-this.N;n=new Te(M,h-M,5,e,{textAlign:0,kM:0,zt:m*2.5,Eb:n*5.33});F=new l_(M,h-M,5,e,F);this.j.push(n);this.j.push(F)}};
g.y(Pb,qi);Pb.prototype.X=function(n){n=new Fq(n,n.byteLength,this.j);if(yu6(n)){for(;n.byteOffset<n.U.byteLength;)for(n.version===0?n.X=eW(n)*(1E3/45):n.version===1&&(n.X=eW(n)*4294967296+eW(n)),n.B=iY(n);n.B>0;n.B--){var m=iY(n),M=iY(n),h=iY(n);m&4&&(m&3)===this.track&&(this.track===0||this.track===1)&&(m=this.U,m.U.push({time:n.X,type:this.track,Jx:M,CZ:h,order:m.U.length}))}s2_(this.U,n);return n.j}return[]};
Pb.prototype.reset=function(){this.U.clear()};g.y(ET,rN);g.w=ET.prototype;g.w.Uq=function(){g.CR(this.CY)};
g.w.T0=function(){this.element.removeEventListener("transitionend",this.T0,!1);g.v9(this.element,"ytp-rollup-mode");this.je(this.cA,!0)};
g.w.Sn=function(){return this.W?this.Uw:this.fP};
g.w.Gu=function(){return this.W?this.fP:this.Uw};
g.w.je=function(n,m){this.cA=n;if(this.j.params.b8){for(var M=0,h=0;h<this.N.length&&M<n.length;h++)this.N[h]===n[M]&&M++;M>0&&M<n.length&&(n=this.N.concat(n.slice(M)));this.nY=this.Uw;this.fP=this.Uw=0;rN.prototype.je.call(this,n);Ze_(this,m)}rN.prototype.je.call(this,n)};XWV.prototype.unload=function(){this.j!=null&&(this.V.removeEventListener("sabrCaptionsDataLoaded",this.j),this.j=null);this.vA=[];this.U=null;this.X=[];this.V.publish("sabrCaptionsBufferedRangesUpdated",this.vA)};
XWV.prototype.q9=function(n){return{formatId:g.Eg(n.info.X6.info,this.xq),x6:n.info.x6+(this.xq?0:1),startTimeMs:n.info.W*1E3,durationMs:n.info.C*1E3}};g.y(Hb,g.rX);Hb.prototype.u8=function(n,m,M){this.WF();m=n.getId();m=m!=null&&m in this.j.U?this.j.U[m]:null;m||(m=n.languageCode,m=this.j.isManifestless?W45(this,m,"386"):W45(this,m));m&&(this.W=n,this.C=m,$QK(this.N,M),this.V.publish("sabrCaptionsTrackChanged",g.Eg(m.info,this.j.xq)))};
Hb.prototype.UN=function(n){var m=this.j.isManifestless?ROo(this,"386"):ROo(this);m=g.Q(m);for(var M=m.next();!M.done;M=m.next())g.KW(this.U,M.value);n.Vn()};
Hb.prototype.WF=function(){this.W&&(this.W=this.C=null,this.N.unload(),this.V.publish("sabrCaptionsTrackChanged",null))};
Hb.prototype.Zf=function(){return""};var ruH="WEBVTT".split("").map(function(n){return n.charCodeAt(0)});
g.y(K46,qi);
K46.prototype.X=function(n,m){n instanceof ArrayBuffer&&(n=g.vg(new Uint8Array(n)));var M=[];n=n.split(E66);for(var h=1;h<n.length;h++){var F=n[h],e=m;if(F!==""&&!HL_.test(F)){var P=z8q.exec(F);if(P&&P.length>=4){var H=SLV(P[1]),z=SLV(P[2])-H;H+=e;var A=(P=P[3])?P.split(" "):[];P={};var b=null;var B="";var V=null,a="";A=g.Q(A);for(var x=A.next();!x.done;x=A.next())if(x=x.value.split(":"),x.length===2){var Y=x[1];switch(x[0]){case "line":x=Y.split(",");x[0].endsWith("%")&&(b=x[0],P.Eb=Number.parseInt(b,
10),x.length===2&&(B=x[1].trim()));break;case "position":x=Y.split(",");V=x[0];P.zt=Number.parseInt(V,10);x.length===2&&(a=x[1].trim());break;case "align":switch(Y){case "start":P.textAlign=0;break;case "middle":P.textAlign=2;break;case "end":P.textAlign=1}}}b||B||(B="end");if(!V)switch(P.textAlign){case 0:P.zt=0;break;case 1:P.zt=100;break;case 2:P.zt=50}if(P.textAlign!=null){b=0;switch(B){case "center":b+=3;break;case "end":b+=6;break;default:b+=0}switch(a){case "line-left":b+=0;break;case "center":b+=
1;break;case "line-right":b+=2;break;default:switch(P.textAlign){case 0:b+=0;break;case 2:b+=1;break;case 1:b+=2}}B=b<0||b>8?7:b;P.kM=B}F=F.substring(z8q.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");a=P;P=F;F={};if(P.indexOf("<")<0&&P.indexOf("&")<0)e=toP(H,z,5,a),z=new l_(H,z,5,e.id,P,!1,g.ms(F)?void 0:F),M.push(e),M.push(z),e.U.push(z);else for(B=P.split(o6_),B.length===1?(P=5,a=toP(H,z,P,a)):(b=P=6,a=Object.assign({Fx:32},a),a=new Te(H,z,b,"_"+Ge++,a)),M.push(a),b=H,V=0;V<B.length;V++)A=B[V],
V%2===0?(x=g.zd("<html>"+A+"</html>"),x.getElementsByTagName("parsererror").length?(Y=x.createElement("span"),Y.appendChild(x.createTextNode(A))):Y=x.firstChild,DQS(this,b,z-(b-H),P,a,V>0,Y,F,M)):b=SLV(A)+e}z8q.lastIndex=0}}return M};
var HL_=/^NOTE/,E66=/(?:\r\n|\r|\n){2,}/,z8q=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),o6_=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.y(zm,g.p);zm.prototype.clear=function(){this.U&&this.U.dispose();this.U=null};
zm.prototype.reset=function(){this.U&&this.U.reset()};
zm.prototype.jU=function(){g.p.prototype.jU.call(this);this.clear()};var y3={windowColor:"#080808",windowOpacity:0,textAlign:2,kM:7,zt:50,Eb:100,isDefault:!0,iI:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.y(TdV,g.CW);g.w=TdV.prototype;g.w.jU=function(){if(this.W||this.BT){var n=this.V.S$();n&&!n.F6()&&n.QV()}else FtY(this,!1);g.CW.prototype.jU.call(this)};
g.w.K6=function(){return this.iq.J("html5_honor_caption_availabilities_in_audio_track")&&this.X!=="LIVE"&&this.X!=="SABR_LIVE"};
g.w.ob=function(){if(this.zv)return this.W||this.BT;if(this.X==="HLS")return this.W;var n=this.getAudioTrack();if(this.K6()){if(!n.captionTracks.length)return!1;if(!this.U)return!0}n=y97(n,g.el(this.iq));return n==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:n==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?oD(this):khw(this)||oD(this)?!0:JuK(this)};
g.w.load=function(){g.CW.prototype.load.call(this);this.k6=this.getAudioTrack();if(this.U)this.j&&(this.HT.clear(),this.W?cuK(this,!0):this.player.getPresentingPlayerType()!==3&&this.U.u8(this.j,"json3",this.Ua),this.X!=="HLS"&&this.W||this.BT||Bb(this)||this.player.mP("captionschanged",g.wj(this.j)));else{var n;this.X==="OFFLINE"?n=new Ms(this.player,this.videoData,this.getAudioTrack()):this.X==="SABR_LIVE"?n=new Hb(this.videoData.U,this.player):this.X==="HLS"?n=new $hY(this.player):this.X==="LIVE"?
n=new KZ(this.videoData.U,this.player):this.X==="INNERTUBE"?n=new g.dX(this.player,this.videoData,this.getAudioTrack()):n=new g.S9(this.player,this.videoData.CY,this.videoData.videoId,g.QnI(this.videoData),this.videoData.Kq,this.videoData.eventId);this.U=n;g.f(this,this.U);this.U.UN(this.Ua)}};
g.w.unload=function(){this.W&&this.j?cuK(this,!1):(this.Ow&&g.KR(this.Ow),this.player.OT("captions"),this.Iz=[],this.U&&this.U.WF(),this.HT.clear(),this.fP&&this.player.Zx(this.fP),this.UI());g.CW.prototype.unload.call(this);this.player.Dg();this.player.mP("captionschanged",{})};
g.w.create=function(){this.ob()&&this.load();var n;a:{var m,M,h;if(this.iq.J("web_player_nitrate_promo_tooltip")&&((m=this.videoData.getPlayerResponse())==null?0:(M=m.captions)==null?0:(h=M.playerCaptionsTracklistRenderer)==null?0:h.enableTouchCaptionsNitrate)){var F,e;if(m=(n=this.videoData.getPlayerResponse())==null?void 0:(F=n.captions)==null?void 0:(e=F.playerCaptionsTracklistRenderer)==null?void 0:e.captionTracks)for(n=g.Q(m),F=n.next();!F.done;F=n.next())if(F=F.value,F.kind==="asr"&&F.languageCode===
"en"){n=!0;break a}}n=!1}n&&this.V.publish("showpromotooltip",this.G.element)};
g.w.Vn=function(){var n=y97(this.player.getAudioTrack(),g.el(this.iq));var m=n==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?bY(this,this.C):n==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&oD(this)?AA(this):khw(this)||this.C||JuK(this)?bY(this,this.C):oD(this)?AA(this):null;if(this.X!=="HLS"&&this.W||this.BT){var M=g.AS(this.U.U,!0);n=[];for(var h=0;h<M.length;h++){var F=M[h],e=g.hs("TRACK");e.setAttribute("kind","subtitles");e.setAttribute("label",g.xj(F));e.setAttribute("srclang",g.yF(F));e.setAttribute("id",
F.toString());this.BT||e.setAttribute("src",this.U.Zf(F,"vtt"));F===m&&e.setAttribute("default","1");n.push(e)}m=this.V.S$();m.w8(n);n=m.Bd();this.rL&&this.eU.D(n.textTracks,"change",this.N9z)}else!this.j&&m&&wp(this,m),this.player.mP("onCaptionsTrackListChanged"),this.player.If("onApiChange")};
g.w.getTrackById=function(n){for(var m=g.AS(this.U.U,!0),M=0;M<m.length;M++)if(m[M].toString()===n)return m[M];return null};
g.w.N9z=function(){for(var n=this.V.S$().Bd().textTracks,m=null,M=0;M<n.length;M++)n[M].mode==="showing"&&(m=this.getTrackById(n[M].id));(this.loaded?this.j:null)!==m&&wp(this,m,!0)};
g.w.vC7=function(){var n;(n=this.U)==null||n.UN(this.Ua)};
g.w.uL6=function(){!this.j&&this.W||this.unload()};
g.w.GB=function(n,m,M,h){if(n){var F;sAo(this,(F=this.j)!=null?F:void 0);this.U.E7()&&(this.Iz=[],this.V.OT("captions"),WT(this.Vi),this.HT.reset());a:{F=this.HT;h=h||0;M=pWS(F,n,M||0);n=[];try{for(var e=g.Q(M),P=e.next();!P.done;P=e.next()){var H=P.value,z=H.trackData,A=H.Rn,b=F.iq.J("safari_live_drm_captions_fix");if(typeof z!=="string"){M=n;var B=M.concat;if(b&&dQP(z))var V=fjY(F,z,A);else{var a=F,x=m,Y=z,X=A,N=h;if(!Ndw(Y))throw Error("Invalid binary caption track data");a.U||(a.U=new Pb(N,x));
V=a.U.X(Y,X)}var C=B.call(M,V)}else{if(z.substring(0,6)==="WEBVTT")var K=n.concat(fjY(F,z,A));else{M=n;var d=M.concat;b:{x=a=void 0;Y=F;X=m;if(z[0]==="{")try{Y.U||(Y.U=new nI(vCw(X)));var t=x=Y.U.X(z,A);break b}catch(u){g.ow(u);t=[];break b}var l=g.zd(z);if(!l||!l.firstChild){var U=Error("Invalid caption track data");U.params=z;throw U;}if(l.firstChild.tagName==="timedtext"){if(Number(l.firstChild.getAttribute("format"))===3){Y.U||(Y.U=new ko(vCw(X),Y.iq));t=a=Y.U.X(l,A);break b}var nN=Error("Unsupported subtitles format in web player (Format2)");
nN.params=z;throw nN;}if(l.firstChild.tagName==="transcript"){var FI=Error("Unsupported subtitles format in web player (Format1)");FI.params=z;throw FI;}var mX=Error("Invalid caption track data");mX.params=z;throw mX;}K=d.call(M,t)}C=K}n=C}var AU=n;break a}catch(u){g.op(F.logger,187101178,"Captions parsing failed: "+u.message+". ");F.clear();AU=[];break a}AU=void 0}this.iq.J("html5_sabr_live_support_subfragmented_captions")&&this.U instanceof Hb&&(m=this.U.N,e=[],AU.length>0&&(e=AU.slice(m.X.length)),
m.X=!m.U||m.U.info.X?[]:AU,AU=e);AU.length>0&&(m=this.j,this.Vg(m,!!m,Bb(this)?"g":this.C?"m":"s"));this.player.Zx(AU,void 0,this.X==="LIVE"||this.X==="SABR_LIVE");!this.C||this.BT||Bb(this)||g.$8(this.iq)||g.CP(this.iq)||g.x_(this.iq)||this.iq.lq==="shortspage"||this.player.isInline()||(g.KR(this.Ow),AU=Bd7({kM:0,zt:5,Eb:5,b8:2,textAlign:0,qP:0,lang:"pl"}),this.vT=[AU],m=["Kliknij ",", by przej\u015b\u0107 do ustawie\u0144"],this.SU||(e=new g.lQ(g.o8()),g.f(this,e),this.SU=e.element),e=AU.end-AU.start,
(P=g.xj(this.j))&&this.vT.push(new l_(AU.start,e,0,AU.id,P)),this.vT.push(new l_(AU.start,e,0,AU.id,m[0]),new l_(AU.start,e,0,AU.id,this.SU,!0),new l_(AU.start,e,0,AU.id,m[1],!0)),this.player.Zx(this.vT),g.W9(this.Ow));!this.C||this.BT||Bb(this)||(this.iq.J("enable_player_captions_persistence_state_machine")?aD(this,!0):g.el(this.iq)?V3(this,!0):xu(this,!0),this.k6&&(this.k6.W=this.j),this.player.Dg());this.C=!1}};
g.w.onCueRangeEnter=function(n){this.Iz.push(n);WT(this.Vi)};
g.w.onCueRangeExit=function(n){g.xq(this.Iz,n);this.U instanceof KZ&&this.U.C&&this.player.a5([n]);WT(this.Vi)};
g.w.getCaptionWindowContainerId=function(){return this.G.element.id};
g.w.Jo9=function(){h8S(this,this.vT);this.vT=null};
g.w.hm=function(){var n=this;if(!this.Xq||!this.W){this.Vi.stop();g.t3B(this.dW);this.Iz.sort(g.Hf);var m=this.Iz;if(this.fP){var M=g.o2(m,function(e){return this.fP.indexOf(e)===-1},this);
M.length&&(m=M)}m=g.Q(m);for(M=m.next();!M.done;M=m.next())n6Y(this,M.value);m=g.Q(Object.entries(this.lq));var h=m.next();for(M={};!h.done;M={V1:void 0,d2:void 0},h=m.next()){var F=g.Q(h.value);h=F.next().value;F=F.next().value;M.V1=h;M.d2=F;this.dW[M.V1]?(M.d2.element.parentNode||(M.d2 instanceof ET||M.d2 instanceof hA||g.qH(this.lq,function(e){return function(P,H){H!==e.V1&&P.j.params.kM===e.d2.j.params.kM&&P.j.params.zt===e.d2.j.params.zt&&P.j.params.Eb===e.d2.j.params.Eb&&(P.dispose(),delete n.lq[H]);
return H===e.V1}}(M),this),this.G.element.appendChild(M.d2.element)),M.d2.je(this.dW[M.V1])):(M.d2.dispose(),delete this.lq[M.V1])}}};
g.w.d8s=function(){qL_(this,{},!0);this.player.mP("captionssettingschanged")};
g.w.tU6=function(){var n=y3.iI;n={background:n.background,backgroundOpacity:n.backgroundOpacity,charEdgeStyle:n.charEdgeStyle,color:n.color,fontFamily:n.fontFamily,fontSizeIncrement:n.fontSizeIncrement,fontStyle:n.bold&&n.italic?3:n.bold?1:n.italic?2:0,textOpacity:n.textOpacity,windowColor:y3.windowColor,windowOpacity:y3.windowOpacity};var m=Idq()||{};m.background!=null&&(n.background=m.background);m.backgroundOverride!=null&&(n.backgroundOverride=m.backgroundOverride);m.backgroundOpacity!=null&&
(n.backgroundOpacity=m.backgroundOpacity);m.backgroundOpacityOverride!=null&&(n.backgroundOpacityOverride=m.backgroundOpacityOverride);m.charEdgeStyle!=null&&(n.charEdgeStyle=m.charEdgeStyle);m.charEdgeStyleOverride!=null&&(n.charEdgeStyleOverride=m.charEdgeStyleOverride);m.color!=null&&(n.color=m.color);m.colorOverride!=null&&(n.colorOverride=m.colorOverride);m.fontFamily!=null&&(n.fontFamily=m.fontFamily);m.fontFamilyOverride!=null&&(n.fontFamilyOverride=m.fontFamilyOverride);m.fontSizeIncrement!=
null&&(n.fontSizeIncrement=m.fontSizeIncrement);m.fontSizeIncrementOverride!=null&&(n.fontSizeIncrementOverride=m.fontSizeIncrementOverride);m.fontStyle!=null&&(n.fontStyle=m.fontStyle);m.fontStyleOverride!=null&&(n.fontStyleOverride=m.fontStyleOverride);m.textOpacity!=null&&(n.textOpacity=m.textOpacity);m.textOpacityOverride!=null&&(n.textOpacityOverride=m.textOpacityOverride);m.windowColor!=null&&(n.windowColor=m.windowColor);m.windowColorOverride!=null&&(n.windowColorOverride=m.windowColorOverride);
m.windowOpacity!=null&&(n.windowOpacity=m.windowOpacity);m.windowOpacityOverride!=null&&(n.windowOpacityOverride=m.windowOpacityOverride);return n};
g.w.Yv=function(n,m){var M={};Object.assign(M,Idq());Object.assign(M,n);qL_(this,M,m);this.player.mP("captionssettingschanged")};
g.w.UI=function(){!this.W&&this.loaded&&(g.p7(this.lq,function(n,m){n.dispose();delete this.lq[m]},this),this.hm())};
g.w.lC=function(n,m){switch(n){case "fontSize":if(isNaN(m))break;n=g.W6(m,-2,4);this.Yv({fontSizeIncrement:n});return n;case "reload":m&&!this.W&&wp(this,this.j,!0);break;case "stickyLoading":m!==void 0&&this.iq.G&&(this.iq.J("enable_player_captions_persistence_state_machine")?aD(this,!(!m||!m.userInitiated)):g.el(this.iq)?V3(this,!!m):xu(this,!!m));break;case "track":return MUH(this,m);case "tracklist":return this.U?g.hF(g.AS(this.U.U,!(!m||!m.includeAsr)),function(M){return g.wj(M)}):[];
case "translationLanguages":return this.U?this.U.B.map(function(M){return Object.assign({},M)}):[];
case "sampleSubtitles":this.W||m===void 0||FtY(this,!!m);break;case "sampleSubtitlesCustomized":this.W||FtY(this,!!m,m);break;case "recommendedTranslationLanguages":return g.P1();case "defaultTranslationSourceTrackIndices":return this.U?this.U.G:[]}};
g.w.getOptions=function(){var n="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.iq.G&&n.push("stickyLoading");return n};
g.w.LO=function(){var n=this.j;if(this.V.U3("captions")){if(this.iq.J("html5_modify_caption_vss_logging")){var m;return(n=(m=this.videoData.KO)!=null?m:null)?{cc:g.c8X(n)}:{}}if(n)return m=n.vssId,n.translationLanguage&&m&&(m="t"+m+"."+g.yF(n)),{cc:m}}return{}};
g.w.RXW=function(n){this.isSubtitlesOn()?(this.iq.J("enable_player_captions_persistence_state_machine")&&n?aD(this,!1):g.el(this.iq)?V3(this,!1):xu(this,!1),sAo(this),wp(this,null,!0)):this.c8(n)};
g.w.c8=function(n){var m=Bb(this)||!this.j?bY(this,!0):this.j;m&&this.GI(m.vssId,"m");this.isSubtitlesOn()||wp(this,m,this.iq.J("enable_player_captions_persistence_state_machine")?n:!0)};
g.w.isSubtitlesOn=function(){return!!this.loaded&&!!this.j&&!Bb(this)};
g.w.RpU=function(){var n=Bb(this);oD(this,n)?wp(this,this.getAudioTrack().U,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.K6()&&(this.C=!1,this.j=null,this.U&&(this.U.dispose(),this.U=null)),this.ob()&&(n?wp(this,bY(this,!1),!1):this.load()))};
g.w.au=function(n){n&&(this.Uw={top:n.top,right:n.right,bottom:n.bottom,left:n.left,width:1-n.left-n.right,height:1-n.top-n.bottom},this.G.element.style.top=this.Uw.top*100+"%",this.G.element.style.left=this.Uw.left*100+"%",this.G.element.style.width=this.Uw.width*100+"%",this.G.element.style.height=this.Uw.height*100+"%",this.G.element.style.position="absolute",n=m87(this))&&(this.G.element.style.width=n.width+"px",this.G.element.style.height=n.height+"px")};
g.w.onVideoDataChange=function(n,m){n==="newdata"&&(this.videoData=m,this.loaded&&this.unload(),this.C=!1,this.j=null,this.U&&(this.U.dispose(),this.U=null,this.player.mP("captionschanged",{})),this.ob()&&this.load())};
g.w.getAudioTrack=function(){return this.player.getAudioTrack()};
g.w.bFi=function(){var n=this.V.S$();n&&!n.F6()&&n.QV();this.V.isFullscreen()?(this.W=this.zv=!0,this.loaded&&this.Vn()):(this.zv=this.iq.controlsType==="3",this.W=ljY(this));wp(this,this.j)};
g.w.LG=function(){var n,m,M,h=(n=this.videoData.getPlayerResponse())==null?void 0:(m=n.captions)==null?void 0:(M=m.playerCaptionsTracklistRenderer)==null?void 0:M.openTranscriptCommand;h&&this.player.qG("innertubeCommand",h)};
g.w.Vg=function(n,m,M){var h=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,F="";n&&(F=n.vssId,F=F.replace(h,""));var e="";n&&n.getId()&&(e=n.getId()||"");n&&n.getXtags()&&(n=n.getXtags(),n=n.replace(h,""),e=e.concat(";"+n));this.X==="HLS"&&(e="");this.V.Vg(m?F:"",m?e:"",M)};
g.w.GI=function(n,m){n=(n||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");n.length>0&&this.V.GI(n,m)};g.WQ("captions",TdV);})(_yt_player);
