(function(g){var window=this;'use strict';var D8q=function(n,m){n.qG("onAutonavCoundownStarted",m)},Seo=function(n){return n.isBackground()&&n.Ra()},tUY=function(n){var m,M,h;
return n==null?void 0:(m=n.playerOverlays)==null?void 0:(M=m.playerOverlayRenderer)==null?void 0:(h=M.autoplay)==null?void 0:h.playerOverlayAutoplayRenderer},ID=function(n,m){m=m===void 0?!1:m;
g.T.call(this,{K:"div",L:"ytp-autonav-endscreen-countdown-overlay"});var M=this;this.N=m;this.cancelCommand=this.B=void 0;this.X=0;n.J("web_post_play_autonav_embiggening")&&g.pR(this.element,"ytp-autonav-endscreen-upnext-updated");this.container=new g.T({K:"div",L:"ytp-autonav-endscreen-countdown-container"});g.f(this,this.container);this.container.Qi(this.element);m=n.S();var h=m.W;this.V=n;this.suggestion=null;this.onVideoDataChange("newdata",this.V.getVideoData());this.D(n,"videodatachange",this.onVideoDataChange);
this.U=new g.T({K:"div",L:"ytp-autonav-endscreen-upnext-container",Y:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},Z:[{K:"div",L:"ytp-autonav-endscreen-topbar-container",Z:[{K:"div",L:"ytp-autonav-endscreen-upnext-header"},{K:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",PT:"{{autoplayAlternativeHeader}}"}]},{K:"a",L:"ytp-autonav-endscreen-link-container",Y:{href:"{{url}}",target:h?
m.k6:""},Z:[{K:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",Y:{style:"{{background}}"},Z:[{K:"div",Y:{"aria-label":"{{timestamp}}"},cT:["ytp-autonav-timestamp"],PT:"{{duration}}"},{K:"div",cT:["ytp-autonav-live-stamp"],PT:"Live"},{K:"div",cT:["ytp-autonav-upcoming-stamp"],PT:"Upcoming"}]},{K:"div",L:"ytp-autonav-endscreen-video-info",Z:[{K:"div",L:"ytp-autonav-endscreen-premium-badge"},{K:"div",L:"ytp-autonav-endscreen-upnext-title",PT:"{{title}}"},{K:"div",L:"ytp-autonav-endscreen-upnext-author",
PT:"{{author}}"},{K:"div",L:"ytp-autonav-view-and-date",PT:"{{views_and_publish_time}}"},{K:"div",L:"ytp-autonav-author-and-view",PT:"{{author_and_views}}"}]}]}]});g.f(this,this.U);this.U.Qi(this.container.element);h||this.D(this.U.m7("ytp-autonav-endscreen-link-container"),"click",this.hU);this.V.createClientVe(this.container.element,this,115127);this.V.createClientVe(this.U.m7("ytp-autonav-endscreen-link-container"),this,115128);this.closeButton=new g.T({K:"button",L:"ytp-autonav-endscreen-upnext-header-close-button",
Y:{"aria-label":"Cancel autoplay"}});g.f(this,this.closeButton);n.J("web_post_play_autonav_embiggening")&&(this.closeButton.listen("click",this.gE,this),this.V.createClientVe(this.closeButton.element,this,115129),this.U.m7("ytp-autonav-endscreen-topbar-container").appendChild(this.closeButton.element));this.overlay=new g.T({K:"div",L:"ytp-autonav-overlay"});g.f(this,this.overlay);this.overlay.Qi(this.container.element);this.j=new g.T({K:"div",L:"ytp-autonav-endscreen-button-container"});g.f(this,
this.j);this.j.Qi(this.container.element);this.cancelButton=new g.T({K:"button",cT:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],Y:{"aria-label":"Cancel autoplay"},PT:"Cancel"});g.f(this,this.cancelButton);this.cancelButton.Qi(this.j.element);this.cancelButton.listen("click",this.gE,this);this.V.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.T({K:"a",cT:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button","ytp-autonav-endscreen-upnext-button-rounded"],Y:{href:"{{url}}",role:"button","aria-label":"Play next video"},PT:"Play Now"});g.f(this,this.playButton);this.playButton.Qi(this.j.element);this.playButton.listen("click",this.hU,this);this.V.createServerVe(this.playButton.element,this.playButton,!0);(m=this.V.getVideoData())&&OL7(this,m);this.W=new g.Rd(function(){p_S(M)},500);
g.f(this,this.W);this.Rc();this.D(n,"autonavvisibility",this.Rc)},$u=function(n){var m=n.V.eS(!0,n.V.isFullscreen());
g.qt(n.container.element,"ytp-autonav-endscreen-small-mode",n.zI(m));g.qt(n.container.element,"ytp-autonav-endscreen-is-premium",!!n.suggestion&&!!n.suggestion.ng6);g.qt(n.V.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!n.V.hN());g.qt(n.V.getRootNode(),"countdown-running",n.o5());g.qt(n.container.element,"ytp-player-content",n.V.hN());n.V.J("web_post_play_autonav_embiggening")||g.W3(n.overlay.element,{width:m.width+"px"});if(n.V.J("web_post_play_autonav_embiggening")){var M=n.V.getRootNode().getBoundingClientRect();
m=Math.min(720,M.width*.5);var h=m*.5625;M=M.height-36-60;h>M&&(h=M,m=16/9*h);g.W3(n.U.m7("ytp-autonav-endscreen-upnext-thumbnail"),{height:h+"px",width:m+"px"});g.W3(n.container.element,{width:m+"px"})}n.o5()||(n.V.hN()?fy5(n,Math.round(v6w(n)/1E3)):fy5(n),m=!!n.suggestion&&!!n.suggestion.tT,h=n.V.hN()||!m,g.qt(n.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!h&&m),g.qt(n.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",h&&!m),n.j.hF(n.V.hN()))},p_S=
function(n){var m=v6w(n),M=Math,h=M.min;
var F=n.X?Date.now()-n.X:0;M=h.call(M,F,m);fy5(n,Math.ceil((m-M)/1E3));m-M<=500&&n.o5()?n.select(!0):n.o5()&&n.W.start()},v6w=function(n){if(n.V.isFullscreen()){var m;
n=(m=n.V.getVideoData())==null?void 0:m.nO;return n===-1||n===void 0?8E3:n}return n.V.hT()>=0?n.V.hT():g.Aq(n.V.S().experiments,"autoplay_time")||1E4},OL7=function(n,m){m=m.getWatchNextResponse();
var M,h;m=(M=tUY(m))==null?void 0:(h=M.nextButton)==null?void 0:h.buttonRenderer;n.B=m==null?void 0:m.navigationEndpoint;M=m==null?void 0:m.trackingParams;n.playButton&&M&&n.V.setTrackingParams(n.playButton.element,M)},fy5=function(n,m){m=m===void 0?-1:m;
n=n.U.m7("ytp-autonav-endscreen-upnext-header");g.eL(n);if(m>=0){m=String(m);var M="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],h="Up next in $SECONDS".indexOf(M);if(h>=0){n.appendChild(g.FG("Up next in $SECONDS".slice(0,h)));var F=g.hs("span");g.td(F,"ytp-autonav-endscreen-upnext-header-countdown-number");g.zl(F,m);n.appendChild(F);n.appendChild(g.FG("Up next in $SECONDS".slice(h+M.length)));return}}g.zl(n,"Up next")},jW=function(n,m){g.T.call(this,{K:"div",
cT:["html5-endscreen","ytp-player-content",m||"base-endscreen"]});this.created=!1;this.player=n},RD=function(n){g.T.call(this,{K:"div",
cT:["ytp-upnext","ytp-player-content"],Y:{"aria-label":"{{aria_label}}"},Z:[{K:"div",L:"ytp-cued-thumbnail-overlay-image",Y:{style:"{{background}}"}},{K:"span",L:"ytp-upnext-top",Z:[{K:"span",L:"ytp-upnext-header",PT:"Up Next"},{K:"span",L:"ytp-upnext-title",PT:"{{title}}"},{K:"span",L:"ytp-upnext-author",PT:"{{author}}"}]},{K:"a",L:"ytp-upnext-autoplay-icon",Y:{role:"button",href:"{{url}}","aria-label":"Play next video"},Z:[{K:"svg",Y:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
Z:[{K:"circle",L:"ytp-svg-autoplay-circle",Y:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{K:"circle",L:"ytp-svg-autoplay-ring",Y:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{K:"path",L:"ytp-svg-fill",Y:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{K:"span",L:"ytp-upnext-bottom",Z:[{K:"span",L:"ytp-upnext-cancel"},{K:"span",L:"ytp-upnext-paused",
PT:"Autoplay is paused"}]}]});this.api=n;this.cancelButton=null;this.B=this.m7("ytp-svg-autoplay-ring");this.X=this.notification=this.U=this.suggestion=null;this.W=new g.Rd(this.k0,5E3,this);this.j=0;var m=this.m7("ytp-upnext-cancel");this.cancelButton=new g.T({K:"button",cT:["ytp-upnext-cancel-button","ytp-button"],Y:{tabindex:"0","aria-label":"Cancel autoplay"},PT:"Cancel"});g.f(this,this.cancelButton);this.cancelButton.listen("click",this.Dh,this);this.cancelButton.Qi(m);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.f(this,this.W);this.api.createClientVe(this.element,this,18788);m=this.m7("ytp-upnext-autoplay-icon");this.D(m,"click",this.H0);this.api.createClientVe(m,this,115130);this.sI();this.D(n,"autonavvisibility",this.sI);this.D(n,"mdxnowautoplaying",this.Nfs);this.D(n,"mdxautoplaycanceled",this.Jj6);g.qt(this.element,"ytp-upnext-mobile",this.api.S().j)},lyq=function(n,m){if(m)return m;
if(n.api.isFullscreen()){var M;n=(M=n.api.getVideoData())==null?void 0:M.nO;return n===-1||n===void 0?8E3:n}return n.api.hT()>=0?n.api.hT():g.Aq(n.api.S().experiments,"autoplay_time")||1E4},qeH=function(n,m){m=lyq(n,m);
var M=Math,h=M.min;var F=(0,g.Vn)()-n.j;M=h.call(M,F,m);m=m===0?1:Math.min(M/m,1);n.B.setAttribute("stroke-dashoffset",""+-211*(m+1));m>=1&&n.o5()&&n.api.getPresentingPlayerType()!==3?n.select(!0):n.o5()&&n.U.start()},TbH=function(n){jW.call(this,n,"videowall-endscreen");
var m=this;this.V=n;this.stills=[];this.X=this.videoData=null;this.W=this.N=!1;this.C=null;g.pR(this.element,"modern-videowall-endscreen");this.j=new g.KH(this);g.f(this,this.j);this.B=new g.Rd(function(){g.pR(m.element,"ytp-show-tiles")},0);
g.f(this,this.B);this.table=new g.lQ({K:"div",L:"ytp-modern-endscreen-content"});g.f(this,this.table);this.table.Qi(this.element);n.getVideoData().U9?this.U=new ID(n,!0):this.U=new RD(n);g.f(this,this.U);g.UV(this.player,this.U.element,4);n.createClientVe(this.element,this,158789);this.hide()},Wb=function(n){return g.cM(n.player)&&n.T9()&&!n.X},CI=function(n){var m=n.hN();
m!==n.N&&(n.N=m,n.player.publish("autonavvisibility"))},GWH=function(n){jW.call(this,n,"subscribecard-endscreen");
this.U=new g.T({K:"div",L:"ytp-subscribe-card",Z:[{K:"img",L:"ytp-author-image",Y:{src:"{{profilePicture}}"}},{K:"div",L:"ytp-subscribe-card-right",Z:[{K:"div",L:"ytp-author-name",PT:"{{author}}"},{K:"div",L:"html5-subscribe-button-container"}]}]});g.f(this,this.U);this.U.Qi(this.element);var m=n.getVideoData();this.subscribeButton=new g.bq("Subscribe",null,"Unsubscribe",null,!0,!1,m.sy,m.subscribed,"trailer-endscreen",null,n,!1);g.f(this,this.subscribeButton);this.subscribeButton.Qi(this.U.m7("html5-subscribe-button-container"));
this.D(n,"videodatachange",this.CP);this.CP();this.hide()},KI=function(n){var m=n.S(),M=g.jx||g.XF?{style:"will-change: opacity"}:void 0,h=m.W,F=["ytp-videowall-still"];
m.j&&F.push("ytp-videowall-show-text");g.T.call(this,{K:"a",cT:F,Y:{href:"{{url}}",target:h?m.k6:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},Z:[{K:"div",L:"ytp-videowall-still-image",Y:{style:"{{background}}"}},{K:"span",L:"ytp-videowall-still-info",Y:{"aria-hidden":"true"},Z:[{K:"span",L:"ytp-videowall-still-info-bg",Z:[{K:"span",L:"ytp-videowall-still-info-content",Y:M,Z:[{K:"span",L:"ytp-videowall-still-info-title",PT:"{{title}}"},
{K:"span",L:"ytp-videowall-still-info-author",PT:"{{author_and_views}}"},{K:"span",L:"ytp-videowall-still-info-live",PT:"Live"},{K:"span",L:"ytp-videowall-still-info-duration",PT:"{{duration}}"}]}]}]},{K:"span",cT:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},Z:[{K:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{K:"span",L:"ytp-videowall-still-listlabel-length",Z:[" (",{K:"span",PT:"{{playlist_length}}"},")"]}]},{K:"span",cT:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},Z:[{K:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{K:"span",L:"ytp-videowall-still-listlabel-length",PT:" (50+)"}]}]});this.suggestion=null;this.j=h;this.api=n;this.U=new g.KH(this);g.f(this,this.U);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.U.D(n,"videodatachange",this.onVideoDataChange);n.createServerVe(this.element,this);this.onVideoDataChange()},rp=function(n){jW.call(this,n,"videowall-endscreen");
var m=this;this.V=n;this.X=0;this.stills=[];this.W=this.videoData=null;this.B=this.C=!1;this.G=null;this.j=new g.KH(this);g.f(this,this.j);this.N=new g.Rd(function(){g.pR(m.element,"ytp-show-tiles")},0);
g.f(this,this.N);var M=new g.T({K:"button",cT:["ytp-button","ytp-endscreen-previous"],Y:{"aria-label":"Previous"},Z:[g.uQ()]});g.f(this,M);M.Qi(this.element);M.listen("click",this.ip,this);this.table=new g.lQ({K:"div",L:"ytp-endscreen-content"});g.f(this,this.table);this.table.Qi(this.element);M=new g.T({K:"button",cT:["ytp-button","ytp-endscreen-next"],Y:{"aria-label":"Next"},Z:[g.n9()]});g.f(this,M);M.Qi(this.element);M.listen("click",this.Zh,this);n.getVideoData().U9?this.U=new ID(n,!0):this.U=
new RD(n);g.f(this,this.U);g.UV(this.player,this.U.element,4);n.createClientVe(this.element,this,158789);this.hide()},dp=function(n){return g.cM(n.player)&&n.T9()&&!n.W},DR=function(n){var m=n.hN();
m!==n.C&&(n.C=m,n.player.publish("autonavvisibility"))},kWo=function(n,m){g.T.call(this,{K:"button",
cT:["ytp-watch-on-youtube-button","ytp-button"],PT:"{{content}}"});this.V=n;this.buttonType=this.buttonType=m;this.bZ();this.buttonType===2&&g.pR(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.bZ);this.hF(!0)},SW=function(n){jW.call(this,n,"watch-again-on-youtube-endscreen");
this.watchButton=new kWo(n,1);g.f(this,this.watchButton);this.watchButton.Qi(this.element);g.u6w(n)&&(this.U=new g.Al(n),g.f(this,this.U),this.j=new g.T({K:"div",cT:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Y:{tabIndex:"-1"},Z:[this.U]}),g.f(this,this.j),this.U.Qi(this.j.element),this.j.Qi(this.element));n.createClientVe(this.element,this,156914);this.hide()},sMq=function(n){g.CW.call(this,n);
var m=this;this.endScreen=null;this.U=this.j=!1;this.listeners=new g.KH(this);g.f(this,this.listeners);var M=n.S();n.isEmbedsShortsMode()?this.endScreen=new SW(n):JO_(n)?(this.j=!0,U8P(this),M.J("delhi_modern_endscreen")?this.endScreen=new TbH(n):this.endScreen=new rp(n)):M.PN?this.endScreen=new GWH(n):this.endScreen=new jW(n);g.f(this,this.endScreen);g.UV(n,this.endScreen.element,4);cO_(this);this.listeners.D(n,"videodatachange",this.onVideoDataChange,this);this.listeners.D(n,g.zV("endscreen"),function(h){m.onCueRangeEnter(h)});
this.listeners.D(n,g.oP("endscreen"),function(h){m.onCueRangeExit(h)})},U8P=function(n){var m=n.player.getVideoData();
if(!m||n.U===m.U9)return!1;n.U=m.U9;return!0},JO_=function(n){n=n.S();
return n.VC&&!n.PN&&!n.disableOrganicUi},cO_=function(n){n.player.OT("endscreen");
var m=n.player.getVideoData();m=new g.E4(Math.max((m.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var M=new g.E4(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});n.player.Zx([m,M])};
g.vM.prototype.hT=g.e3(8,function(){return this.app.hT()});
g.C8.prototype.hT=g.e3(7,function(){return this.getVideoData().t5});
g.tc.prototype.fQ=g.e3(6,function(n){this.zA().fQ(n)});
g.PS.prototype.fQ=g.e3(5,function(n){this.YP!==n&&(this.YP=n,this.ZU())});
g.y(ID,g.T);g.w=ID.prototype;g.w.gm=function(n){this.suggestion!==n&&(this.suggestion=n,g.yQ(this.U,n),this.playButton.updateValue("url",this.suggestion.h6()),$u(this))};
g.w.o5=function(){return this.X>0};
g.w.Bv=function(){this.o5()||(this.X=Date.now(),p_S(this),D8q(this.V,v6w(this)),g.qt(this.V.getRootNode(),"countdown-running",this.o5()))};
g.w.Hw=function(){this.s3();p_S(this);var n=this.U.m7("ytp-autonav-endscreen-upnext-header");n&&g.zl(n,"Up next")};
g.w.s3=function(){this.o5()&&(this.W.stop(),this.X=0)};
g.w.select=function(n){this.V.nextVideo(!1,n===void 0?!1:n);this.s3()};
g.w.hU=function(n){g.Vz(n,this.V)&&(n.currentTarget===this.playButton.element?this.V.logClick(this.playButton.element):n.currentTarget===this.U.m7("ytp-autonav-endscreen-link-container")&&(n=this.U.m7("ytp-autonav-endscreen-link-container"),this.V.logVisibility(n,!0),this.V.logClick(n)),this.B?(this.V.qG("innertubeCommand",this.B),this.s3()):this.select())};
g.w.gE=function(){this.V.logClick(this.cancelButton.element);g.qG(this.V,!0);this.cancelCommand&&this.V.qG("innertubeCommand",this.cancelCommand)};
g.w.onVideoDataChange=function(n,m){OL7(this,m);n=m.getWatchNextResponse();var M,h;n=(M=tUY(n))==null?void 0:(h=M.cancelButton)==null?void 0:h.buttonRenderer;this.cancelCommand=n==null?void 0:n.command};
g.w.Rc=function(){var n=this.V.hN();this.N&&this.Wd!==n&&this.hF(n);$u(this);this.V.logVisibility(this.container.element,n);this.V.logVisibility(this.cancelButton.element,n);this.V.logVisibility(this.U.m7("ytp-autonav-endscreen-link-container"),n);this.V.logVisibility(this.playButton.element,n)};
g.w.zI=function(n){return n.width<400||n.height<459};g.y(jW,g.T);g.w=jW.prototype;g.w.create=function(){this.created=!0};
g.w.destroy=function(){this.created=!1};
g.w.T9=function(){return!1};
g.w.hN=function(){return!1};
g.w.XC=function(){return!1};g.y(RD,g.T);g.w=RD.prototype;g.w.k0=function(){this.notification&&(this.W.stop(),this.N2(this.X),this.X=null,this.notification.close(),this.notification=null)};
g.w.gm=function(n){this.suggestion=n;g.yQ(this,n,"hqdefault.jpg")};
g.w.sI=function(){this.hF(this.api.hN());this.api.logVisibility(this.element,this.api.hN());this.api.logVisibility(this.m7("ytp-upnext-autoplay-icon"),this.api.hN());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.hN())};
g.w.LPT=function(){window.focus();this.k0()};
g.w.Bv=function(n){var m=this;this.o5()||(g.Sy("a11y-announce","Up Next "+this.suggestion.title),this.j=(0,g.Vn)(),this.U=new g.Rd(function(){qeH(m,n)},25),qeH(this,n),D8q(this.api,lyq(this,n)));
g.v9(this.element,"ytp-upnext-autoplay-paused")};
g.w.hide=function(){g.T.prototype.hide.call(this)};
g.w.o5=function(){return!!this.U};
g.w.Hw=function(){this.s3();this.j=(0,g.Vn)();qeH(this);g.pR(this.element,"ytp-upnext-autoplay-paused")};
g.w.s3=function(){this.o5()&&(this.U.dispose(),this.U=null)};
g.w.select=function(n){n=n===void 0?!1:n;if(this.api.S().J("autonav_notifications")&&n&&window.Notification&&typeof document.hasFocus==="function"){var m=Notification.permission;m==="default"?Notification.requestPermission():m!=="granted"||document.hasFocus()||(this.k0(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.FH()}),this.X=this.D(this.notification,"click",this.LPT),this.W.start())}this.s3();this.api.nextVideo(!1,n)};
g.w.H0=function(n){!g.H3(this.cancelButton.element,n.target)&&g.Vz(n,this.api)&&(this.api.hN()&&this.api.logClick(this.m7("ytp-upnext-autoplay-icon")),this.select())};
g.w.Dh=function(){this.api.hN()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.qG(this.api,!0)};
g.w.Nfs=function(n){this.api.getPresentingPlayerType();this.show();this.Bv(n)};
g.w.Jj6=function(){this.api.getPresentingPlayerType();this.s3();this.hide()};
g.w.jU=function(){this.s3();this.k0();g.T.prototype.jU.call(this)};g.y(TbH,jW);g.w=TbH.prototype;g.w.create=function(){jW.prototype.create.call(this);var n=this.player.getVideoData();n&&(this.videoData=n);this.ZV();this.j.D(this.player,"appresize",this.ZV);this.j.D(this.player,"onVideoAreaChange",this.ZV);this.j.D(this.player,"videodatachange",this.onVideoDataChange);this.j.D(this.player,"autonavchange",this.hD);this.j.D(this.player,"onAutonavCancelled",this.SH);n=this.videoData.autonavState;n!==this.C&&this.hD(n);this.j.D(this.element,"transitionend",this.GN)};
g.w.destroy=function(){g.Xo(this.j);g.qo(this.stills);this.stills=[];jW.prototype.destroy.call(this);g.v9(this.element,"ytp-show-tiles");this.B.stop();this.C=this.videoData.autonavState};
g.w.T9=function(){return this.videoData.autonavState!==1};
g.w.show=function(){var n=this.Wd;jW.prototype.show.call(this);g.v9(this.element,"ytp-show-tiles");this.player.S().j?g.CR(this.B):this.B.start();(this.W||this.X&&this.X!==this.videoData.clientPlaybackNonce)&&g.qG(this.player,!1);Wb(this)?(CI(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||Seo(this.player.BN())&&this.player.J("web_player_pip_logging_fix")?this.U.select(!0):this.U.Bv():this.videoData.autonavState===3&&this.U.Hw()):(g.qG(this.player,!0),CI(this));n!==this.Wd&&
this.player.logVisibility(this.element,!0)};
g.w.hide=function(){var n=this.Wd;jW.prototype.hide.call(this);this.U.Hw();CI(this);n!==this.Wd&&this.player.logVisibility(this.element,!1)};
g.w.GN=function(n){n.target===this.element&&this.ZV()};
g.w.ZV=function(){var n,m,M,h;var F=((n=this.videoData)==null?0:(m=n.suggestions)==null?0:m.length)?(M=this.videoData)==null?void 0:M.suggestions:[(h=this.videoData)==null?void 0:g.lu(h)];if(F.length){m=this.V.eS(!0,this.V.isFullscreen());n=Math.floor((m.width-64+16)/(g.W6(m.width*.27,250,450)+16));m=Math.min(3,Math.floor((m.height-64)/((m.width-64-(n-1)*16)/n*.5625+70)));g.lP(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.pR(this.element,"ytp-modern-endscreen-limit-rows-"+m);g.qt(this.element,"ytp-modern-endscreen-single-item",n===1);g.qt(this.element,"ytp-modern-endscreen-row-0",m===0);n=this.table.element;n.ariaLive="polite";this.U.gm(g.lu(this.videoData));this.U instanceof ID&&$u(this.U);g.qt(this.element,"ytp-endscreen-takeover",Wb(this));CI(this);m=0;n.ariaBusy="true";M=F.length;for(h=0;h<M;h++){var e=h%M,P=this.stills[h];P||(P=new g.NM(this.player),this.stills[h]=P,n.appendChild(P.element));g.nzq(P,F[e]);m++}this.stills.length=
m}};
g.w.onVideoDataChange=function(){var n=this.player.getVideoData({playerType:1});this.videoData!==n&&(n!=null&&g.lu(n)?(this.videoData=n,this.ZV()):this.player.uq("missg",{vid:(n==null?void 0:n.videoId)||"",cpn:(n==null?void 0:n.clientPlaybackNonce)||""}))};
g.w.XC=function(){return this.U.o5()};
g.w.hD=function(n){n===1?(this.W=!1,this.X=this.videoData.clientPlaybackNonce,this.U.s3(),this.Wd&&this.ZV()):(this.W=!0,this.Wd&&Wb(this)&&(n===2?this.U.Bv():n===3&&this.U.Hw()))};
g.w.SH=function(n){if(n){for(n=0;n<this.stills.length;n++)this.V.logVisibility(this.stills[n].element,!0);this.hD(1)}else this.X=null,this.W=!1;this.ZV()};
g.w.hN=function(){return this.Wd&&Wb(this)};g.y(GWH,jW);GWH.prototype.CP=function(){var n=this.player.getVideoData();this.U.update({profilePicture:n.profilePicture,author:n.author});this.subscribeButton.channelId=n.sy;var m=this.subscribeButton;n.subscribed?m.U():m.j()};g.y(KI,g.T);KI.prototype.select=function(){this.api.F4(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.KL||void 0)&&this.api.logClick(this.element)};
KI.prototype.onClick=function(n){if(g.iy(this.api.S())&&this.api.J("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var m=this.suggestion.h6(),M={};g.kI(this.api,M);m=g.ee(m,M);g.xf(m,this.api,n)}else g.Vz(n,this.api,this.j,this.suggestion.sessionData||void 0)&&this.select()};
KI.prototype.onKeyPress=function(n){switch(n.keyCode){case 13:case 32:n.defaultPrevented||(this.select(),n.preventDefault())}};
KI.prototype.onVideoDataChange=function(){var n=this.api.getVideoData(),m=this.api.S();this.j=n.u2?!1:m.W};g.y(rp,jW);g.w=rp.prototype;g.w.create=function(){jW.prototype.create.call(this);var n=this.player.getVideoData();n&&(this.videoData=n);this.uv();this.j.D(this.player,"appresize",this.uv);this.j.D(this.player,"onVideoAreaChange",this.uv);this.j.D(this.player,"videodatachange",this.onVideoDataChange);this.j.D(this.player,"autonavchange",this.sV);this.j.D(this.player,"onAutonavCancelled",this.Y_);n=this.videoData.autonavState;n!==this.G&&this.sV(n);this.j.D(this.element,"transitionend",this.rz)};
g.w.destroy=function(){g.Xo(this.j);g.qo(this.stills);this.stills=[];jW.prototype.destroy.call(this);g.v9(this.element,"ytp-show-tiles");this.N.stop();this.G=this.videoData.autonavState};
g.w.T9=function(){return this.videoData.autonavState!==1};
g.w.show=function(){var n=this.Wd;jW.prototype.show.call(this);g.v9(this.element,"ytp-show-tiles");this.player.S().j?g.CR(this.N):this.N.start();(this.B||this.W&&this.W!==this.videoData.clientPlaybackNonce)&&g.qG(this.player,!1);dp(this)?(DR(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||Seo(this.player.BN())&&this.player.J("web_player_pip_logging_fix")?this.U.select(!0):this.U.Bv():this.videoData.autonavState===3&&this.U.Hw()):(g.qG(this.player,!0),DR(this));n!==this.Wd&&
this.player.logVisibility(this.element,!0)};
g.w.hide=function(){var n=this.Wd;jW.prototype.hide.call(this);this.U.Hw();DR(this);n!==this.Wd&&this.player.logVisibility(this.element,!1)};
g.w.rz=function(n){n.target===this.element&&this.uv()};
g.w.uv=function(){var n,m,M,h;var F=((n=this.videoData)==null?0:(m=n.suggestions)==null?0:m.length)?(M=this.videoData)==null?void 0:M.suggestions:[(h=this.videoData)==null?void 0:g.lu(h)];if(F.length){g.pR(this.element,"ytp-endscreen-paginate");var e=this.V.eS(!0,this.V.isFullscreen());if(n=g.df(this.V))n=n.Bn()?48:32,e.width-=n*2;var P=e.width/e.height;h=96/54;m=n=2;var H=Math.max(e.width/96,2),z=Math.max(e.height/54,2);M=F.length;var A=M*4;for(A-=4;A>0&&(n<H||m<z);){var b=n/2,B=m/2,V=n<=H-2&&A>=
B*4,a=m<=z-2&&A>=b*4;if((b+1)/B*h/P>P/(b/(B+1)*h)&&a)A-=b*4,m+=2;else if(V)A-=B*4,n+=2;else if(a)A-=b*4,m+=2;else break}h=!1;A>=12&&M*4-A<=6&&(m>=4||n>=4)&&(h=!0);A=n*96;H=m*54;P=A/H<P?e.height/H:e.width/A;P=Math.min(P,2);A=Math.floor(Math.min(e.width,A*P));H=Math.floor(Math.min(e.height,H*P));e=this.table.element;e.ariaLive="polite";g.fV(e,A,H);g.W3(e,{marginLeft:A/-2+"px",marginTop:H/-2+"px"});this.U.gm(g.lu(this.videoData));this.U instanceof ID&&$u(this.U);g.qt(this.element,"ytp-endscreen-takeover",
dp(this));DR(this);A+=4;H+=4;P=0;e.ariaBusy="true";for(z=0;z<n;z++)for(b=0;b<m;b++)if(B=P,a=0,h&&z>=n-2&&b>=m-2?a=1:b%2===0&&z%2===0&&(b<2&&z<2?b===0&&z===0&&(a=2):a=2),B=g.CG(B+this.X,M),a!==0){V=this.stills[P];V||(V=new KI(this.player),this.stills[P]=V,e.appendChild(V.element));var x=Math.floor(H*b/m),Y=Math.floor(A*z/n),X=Math.floor(H*(b+a)/m)-x-4,N=Math.floor(A*(z+a)/n)-Y-4;g.SL(V.element,Y,x);g.fV(V.element,N,X);g.W3(V.element,"transitionDelay",(b+z)/20+"s");g.qt(V.element,"ytp-videowall-still-mini",
a===1);g.qt(V.element,"ytp-videowall-still-large",a>2);a=Math.max(N,X);g.qt(V.element,"ytp-videowall-still-round-large",a>=256);g.qt(V.element,"ytp-videowall-still-round-medium",a>96&&a<256);g.qt(V.element,"ytp-videowall-still-round-small",a<=96);B=F[B];V.suggestion!==B&&(V.suggestion=B,a=V.api.S(),x=g.On(V.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.yQ(V,B,x),g.iy(a)&&!V.api.J("web_player_log_click_before_generating_ve_conversion_params")&&(a=B.h6(),x={},g.WM(V.api,"addEmbedsConversionTrackingParams",
[x]),a=g.ee(a,x),V.updateValue("url",a)),(B=(B=B.sessionData)&&B.itct)&&V.api.setTrackingParams(V.element,B));P++}e.ariaBusy="false";g.qt(this.element,"ytp-endscreen-paginate",P<M);for(F=this.stills.length-1;F>=P;F--)n=this.stills[F],g.EZ(n.element),g.lJ(n);this.stills.length=P}};
g.w.onVideoDataChange=function(){var n=this.player.getVideoData({playerType:1});this.videoData!==n&&(n!=null&&g.lu(n)?(this.X=0,this.videoData=n,this.uv()):this.player.uq("missg",{vid:(n==null?void 0:n.videoId)||"",cpn:(n==null?void 0:n.clientPlaybackNonce)||""}))};
g.w.Zh=function(){this.X+=this.stills.length;this.uv()};
g.w.ip=function(){this.X-=this.stills.length;this.uv()};
g.w.XC=function(){return this.U.o5()};
g.w.sV=function(n){n===1?(this.B=!1,this.W=this.videoData.clientPlaybackNonce,this.U.s3(),this.Wd&&this.uv()):(this.B=!0,this.Wd&&dp(this)&&(n===2?this.U.Bv():n===3&&this.U.Hw()))};
g.w.Y_=function(n){if(n){for(n=0;n<this.stills.length;n++)this.V.logVisibility(this.stills[n].element,!0);this.sV(1)}else this.W=null,this.B=!1;this.uv()};
g.w.hN=function(){return this.Wd&&dp(this)};g.y(kWo,g.T);g.w=kWo.prototype;g.w.bZ=function(){switch(this.buttonType){case 1:var n="Watch again on YouTube";var m=156915;break;case 2:n="Continue watching on YouTube";m=156942;break;default:n="Continue watching on YouTube",m=156942}this.update({content:n});this.V.hasVe(this.element)&&this.V.destroyVe(this.element);this.V.createClientVe(this.element,this,m)};
g.w.onClick=function(n){this.V.J("web_player_log_click_before_generating_ve_conversion_params")&&this.V.logClick(this.element);g.xf(this.getVideoUrl(),this.V,n);this.V.J("web_player_log_click_before_generating_ve_conversion_params")||this.V.logClick(this.element)};
g.w.getVideoUrl=function(){var n=!0;switch(this.buttonType){case 1:n=!0;break;case 2:n=!1}n=this.V.getVideoUrl(n,!1,!1,!0);var m=this.V.S();if(g.iy(m)){var M={};g.iy(m)&&g.WM(this.V,"addEmbedsConversionTrackingParams",[M]);n=g.ee(n,M)}return n};
g.w.logVisibility=function(){this.V.logVisibility(this.element,this.Wd&&this.k6)};
g.w.show=function(){g.T.prototype.show.call(this);this.logVisibility()};
g.w.hide=function(){g.T.prototype.hide.call(this);this.logVisibility()};
g.w.Xf=function(n){g.T.prototype.Xf.call(this,n);this.logVisibility()};g.y(SW,jW);SW.prototype.hasSuggestions=function(){var n;return(n=this.U)==null?void 0:n.hasSuggestions()};
SW.prototype.show=function(){if(this.player.getPlayerState()!==3){jW.prototype.show.call(this);var n=this.j;if(n){var m=this.U.hasSuggestions();g.qt(this.element,"ytp-shorts-branded-ui",m);m?n.show():n.hide()}var M;(M=g.df(this.player))==null||M.fQ(!0);this.player.logVisibility(this.element,!0);this.watchButton.Xf(!0)}};
SW.prototype.hide=function(){jW.prototype.hide.call(this);var n;(n=g.df(this.player))==null||n.fQ(!1);this.player.logVisibility(this.element,!1);this.watchButton.Xf(!1)};g.y(sMq,g.CW);g.w=sMq.prototype;g.w.ob=function(){var n=this.player.getVideoData(),m=n.mutedAutoplay&&(n.limitedPlaybackDurationInSeconds>0||n.endSeconds>0||n.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!m)return!0;var M;var h=!!((n==null?0:g.lu(n))||(n==null?0:(M=n.suggestions)==null?0:M.length));h=!JO_(this.player)||h;n=n.oX;M=this.player.N9();return h&&!n&&!M&&!m};
g.w.hN=function(){return this.endScreen.hN()};
g.w.QpU=function(){return this.hN()?this.endScreen.XC():!1};
g.w.jU=function(){this.player.OT("endscreen");g.CW.prototype.jU.call(this)};
g.w.load=function(){var n=this.player.getVideoData();var m=n.transitionEndpointAtEndOfStream;if(m&&m.videoId){var M=this.player.VX().WK.get("heartbeat"),h=g.lu(n);!h||m.videoId!==h.videoId||n.F0?(this.player.F4(m.videoId,void 0,void 0,!0,!0,m),M&&M.a_("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),n=!0):n=!1}else n=!1;n||(g.CW.prototype.load.call(this),this.endScreen.show())};
g.w.unload=function(){g.CW.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.w.onCueRangeEnter=function(n){this.ob()&&(this.endScreen.created||this.endScreen.create(),n.getId()==="load"&&this.load())};
g.w.onCueRangeExit=function(n){n.getId()==="load"&&this.loaded&&this.unload()};
g.w.onVideoDataChange=function(){cO_(this);this.j&&U8P(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.endScreen=new rp(this.player),g.f(this,this.endScreen),g.UV(this.player,this.endScreen.element,4))};g.WQ("endscreen",sMq);})(_yt_player);
